// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetEnum.proto

package com.supercat.growstone.network.messages;

/**
 * Protobuf enum {@code PacketType}
 */
public enum PacketType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Ping = 0;</code>
   */
  Ping(0),
  /**
   * <code>LoginRequest = 1;</code>
   */
  LoginRequest(1),
  /**
   * <code>LoginResponse = 2;</code>
   */
  LoginResponse(2),
  /**
   * <code>ChangeEquipAvatarRequest = 3;</code>
   */
  ChangeEquipAvatarRequest(3),
  /**
   * <code>ChangeEquipAvatarResponse = 4;</code>
   */
  ChangeEquipAvatarResponse(4),
  /**
   * <code>GrowthLevelUpRequest = 5;</code>
   */
  GrowthLevelUpRequest(5),
  /**
   * <code>GrowthLevelUpResponse = 6;</code>
   */
  GrowthLevelUpResponse(6),
  /**
   * <code>GrowthPromoteRequest = 7;</code>
   */
  GrowthPromoteRequest(7),
  /**
   * <code>GrowthPromoteResponse = 8;</code>
   */
  GrowthPromoteResponse(8),
  /**
   * <code>GrowthLimitBreakRequest = 9;</code>
   */
  GrowthLimitBreakRequest(9),
  /**
   * <code>GrowthLimitBreakResponse = 10;</code>
   */
  GrowthLimitBreakResponse(10),
  /**
   * <code>PartsSlotLevelUpRequest = 11;</code>
   */
  PartsSlotLevelUpRequest(11),
  /**
   * <code>PartsSlotLevelUpResponse = 12;</code>
   */
  PartsSlotLevelUpResponse(12),
  /**
   * <code>GrowthEquipPartsRequest = 13;</code>
   */
  GrowthEquipPartsRequest(13),
  /**
   * <code>GrowthEquipPartsResponse = 14;</code>
   */
  GrowthEquipPartsResponse(14),
  /**
   * <code>LogoutRequest = 15;</code>
   */
  LogoutRequest(15),
  /**
   * <code>LogoutResponse = 16;</code>
   */
  LogoutResponse(16),
  /**
   * <code>LogoutNotify = 17;</code>
   */
  LogoutNotify(17),
  /**
   * <code>MailRequest = 18;</code>
   */
  MailRequest(18),
  /**
   * <code>MailResponse = 19;</code>
   */
  MailResponse(19),
  /**
   * <code>MailReadRequest = 20;</code>
   */
  MailReadRequest(20),
  /**
   * <code>MailReadResponse = 21;</code>
   */
  MailReadResponse(21),
  /**
   * <code>MailNotify = 22;</code>
   */
  MailNotify(22),
  /**
   * <code>CollectionLevelUpRequest = 23;</code>
   */
  CollectionLevelUpRequest(23),
  /**
   * <code>CollectionLevelUpResponse = 24;</code>
   */
  CollectionLevelUpResponse(24),
  /**
   * <code>CollectionRequest = 25;</code>
   */
  CollectionRequest(25),
  /**
   * <code>CollectionResponse = 26;</code>
   */
  CollectionResponse(26),
  /**
   * <code>SyncItemCountRequest = 27;</code>
   */
  SyncItemCountRequest(27),
  /**
   * <code>SyncItemCountResponse = 28;</code>
   */
  SyncItemCountResponse(28),
  /**
   * <code>PartsSlotRequest = 29;</code>
   */
  PartsSlotRequest(29),
  /**
   * <code>PartsSlotResponse = 30;</code>
   */
  PartsSlotResponse(30),
  /**
   * <code>StageClearSaveRequest = 31;</code>
   */
  StageClearSaveRequest(31),
  /**
   * <code>StageClearSaveResponse = 32;</code>
   */
  StageClearSaveResponse(32),
  /**
   * <code>ChangePortraitIconRequest = 33;</code>
   */
  ChangePortraitIconRequest(33),
  /**
   * <code>ChangePortraitIconResponse = 34;</code>
   */
  ChangePortraitIconResponse(34),
  /**
   * <code>ChangePlayerNameRequest = 35;</code>
   */
  ChangePlayerNameRequest(35),
  /**
   * <code>ChangePlayerNameResponse = 36;</code>
   */
  ChangePlayerNameResponse(36),
  /**
   * <code>StatsRequest = 37;</code>
   */
  StatsRequest(37),
  /**
   * <code>StatsResponse = 38;</code>
   */
  StatsResponse(38),
  /**
   * <code>CharacterStatGrowthRequest = 39;</code>
   */
  CharacterStatGrowthRequest(39),
  /**
   * <code>CharacterStatGrowthResponse = 40;</code>
   */
  CharacterStatGrowthResponse(40),
  /**
   * <code>CharacterStatGrowthLevelUpRequest = 41;</code>
   */
  CharacterStatGrowthLevelUpRequest(41),
  /**
   * <code>CharacterStatGrowthLevelUpResponse = 42;</code>
   */
  CharacterStatGrowthLevelUpResponse(42),
  /**
   * <code>EquipPresetRequest = 43;</code>
   */
  EquipPresetRequest(43),
  /**
   * <code>EquipPresetResponse = 44;</code>
   */
  EquipPresetResponse(44),
  /**
   * <code>EquipPresetEquipRequest = 45;</code>
   */
  EquipPresetEquipRequest(45),
  /**
   * <code>EquipPresetEquipResponse = 46;</code>
   */
  EquipPresetEquipResponse(46),
  /**
   * <code>EquipPresetUnEquipRequest = 47;</code>
   */
  EquipPresetUnEquipRequest(47),
  /**
   * <code>EquipPresetUnEquipResponse = 48;</code>
   */
  EquipPresetUnEquipResponse(48),
  /**
   * <code>EquipPresetNameChangeRequest = 51;</code>
   */
  EquipPresetNameChangeRequest(51),
  /**
   * <code>EquipPresetNameChangeResponse = 52;</code>
   */
  EquipPresetNameChangeResponse(52),
  /**
   * <code>EquipPresetIndexChangeRequest = 53;</code>
   */
  EquipPresetIndexChangeRequest(53),
  /**
   * <code>EquipPresetIndexChangeResponse = 54;</code>
   */
  EquipPresetIndexChangeResponse(54),
  /**
   * <code>StatsNotify = 55;</code>
   */
  StatsNotify(55),
  /**
   * <code>PlayerLevelUpNotify = 56;</code>
   */
  PlayerLevelUpNotify(56),
  /**
   * <code>DailyDungeonStartRequest = 57;</code>
   */
  DailyDungeonStartRequest(57),
  /**
   * <code>DailyDungeonStartResponse = 58;</code>
   */
  DailyDungeonStartResponse(58),
  /**
   * <code>DailyDungeonClearRequest = 59;</code>
   */
  DailyDungeonClearRequest(59),
  /**
   * <code>DailyDungeonClearResponse = 60;</code>
   */
  DailyDungeonClearResponse(60),
  /**
   * <code>DailyDungeonRequest = 61;</code>
   */
  DailyDungeonRequest(61),
  /**
   * <code>DailyDungeonResponse = 62;</code>
   */
  DailyDungeonResponse(62),
  /**
   * <code>DailyDungeonViewAdvertiseRequest = 63;</code>
   */
  DailyDungeonViewAdvertiseRequest(63),
  /**
   * <code>DailyDungeonViewAdvertiseResponse = 64;</code>
   */
  DailyDungeonViewAdvertiseResponse(64),
  /**
   * <code>RaidDungeonStartRequest = 65;</code>
   */
  RaidDungeonStartRequest(65),
  /**
   * <code>RaidDungeonStartResponse = 66;</code>
   */
  RaidDungeonStartResponse(66),
  /**
   * <code>RaidDungeonClearRequest = 67;</code>
   */
  RaidDungeonClearRequest(67),
  /**
   * <code>RaidDungeonClearResponse = 68;</code>
   */
  RaidDungeonClearResponse(68),
  /**
   * <code>RaidDungeonRequest = 69;</code>
   */
  RaidDungeonRequest(69),
  /**
   * <code>RaidDungeonResponse = 70;</code>
   */
  RaidDungeonResponse(70),
  /**
   * <code>RaidDungeonViewAdvertiseRequest = 71;</code>
   */
  RaidDungeonViewAdvertiseRequest(71),
  /**
   * <code>RaidDungeonViewAdvertiseResponse = 72;</code>
   */
  RaidDungeonViewAdvertiseResponse(72),
  /**
   * <code>TowerStartRequest = 73;</code>
   */
  TowerStartRequest(73),
  /**
   * <code>TowerStartResponse = 74;</code>
   */
  TowerStartResponse(74),
  /**
   * <code>TowerClearRequest = 75;</code>
   */
  TowerClearRequest(75),
  /**
   * <code>TowerClearResponse = 76;</code>
   */
  TowerClearResponse(76),
  /**
   * <code>TowerRequest = 77;</code>
   */
  TowerRequest(77),
  /**
   * <code>TowerResponse = 78;</code>
   */
  TowerResponse(78),
  /**
   * <code>CooperativeRaidDungeonRequest = 79;</code>
   */
  CooperativeRaidDungeonRequest(79),
  /**
   * <code>CooperativeRaidDungeonResponse = 80;</code>
   */
  CooperativeRaidDungeonResponse(80),
  /**
   * <code>CompetitiveRaidDungeonRequest = 81;</code>
   */
  CompetitiveRaidDungeonRequest(81),
  /**
   * <code>CompetitiveRaidDungeonResponse = 82;</code>
   */
  CompetitiveRaidDungeonResponse(82),
  /**
   * <code>CompetitiveRaidDungeonRankRequest = 83;</code>
   */
  CompetitiveRaidDungeonRankRequest(83),
  /**
   * <code>CompetitiveRaidDungeonRankResponse = 84;</code>
   */
  CompetitiveRaidDungeonRankResponse(84),
  /**
   * <code>FriendListRequest = 85;</code>
   */
  FriendListRequest(85),
  /**
   * <code>FriendListResponse = 86;</code>
   */
  FriendListResponse(86),
  /**
   * <code>AddFriendRequest = 87;</code>
   */
  AddFriendRequest(87),
  /**
   * <code>AddFriendResponse = 88;</code>
   */
  AddFriendResponse(88),
  /**
   * <code>DeleteFriendRequest = 89;</code>
   */
  DeleteFriendRequest(89),
  /**
   * <code>DeleteFriendResponse = 90;</code>
   */
  DeleteFriendResponse(90),
  /**
   * <code>GiveFriendGiftRequest = 91;</code>
   */
  GiveFriendGiftRequest(91),
  /**
   * <code>GiveFriendGiftResponse = 92;</code>
   */
  GiveFriendGiftResponse(92),
  /**
   * <code>SearchFriendRequest = 93;</code>
   */
  SearchFriendRequest(93),
  /**
   * <code>SearchFriendResponse = 94;</code>
   */
  SearchFriendResponse(94),
  /**
   * <code>AddFriendCancelRequest = 95;</code>
   */
  AddFriendCancelRequest(95),
  /**
   * <code>AddFriendCancelResponse = 96;</code>
   */
  AddFriendCancelResponse(96),
  /**
   * <code>RecommendFriendRequest = 98;</code>
   */
  RecommendFriendRequest(98),
  /**
   * <code>RecommendFriendResponse = 99;</code>
   */
  RecommendFriendResponse(99),
  /**
   * <code>AddFriendNotify = 100;</code>
   */
  AddFriendNotify(100),
  /**
   * <code>DeleteFriendNotify = 101;</code>
   */
  DeleteFriendNotify(101),
  /**
   * <code>ChangeFriendStateNotify = 102;</code>
   */
  ChangeFriendStateNotify(102),
  /**
   * <code>BlockPlayerRequest = 103;</code>
   */
  BlockPlayerRequest(103),
  /**
   * <code>BlockPlayerResponse = 104;</code>
   */
  BlockPlayerResponse(104),
  /**
   * <code>UnBlockPlayerRequest = 105;</code>
   */
  UnBlockPlayerRequest(105),
  /**
   * <code>UnBlockPlayerResponse = 106;</code>
   */
  UnBlockPlayerResponse(106),
  /**
   * <code>PlayerBlockListRequest = 107;</code>
   */
  PlayerBlockListRequest(107),
  /**
   * <code>PlayerBlockListResponse = 108;</code>
   */
  PlayerBlockListResponse(108),
  /**
   * <code>CheatRequest = 109;</code>
   */
  CheatRequest(109),
  /**
   * <code>CheatResponse = 110;</code>
   */
  CheatResponse(110),
  /**
   * <code>ViewAdvertiseRequest = 111;</code>
   */
  ViewAdvertiseRequest(111),
  /**
   * <code>ViewAdvertiseResponse = 112;</code>
   */
  ViewAdvertiseResponse(112),
  /**
   * <code>AvatarNotify = 113;</code>
   */
  AvatarNotify(113),
  /**
   * <code>GrowthNotify = 114;</code>
   */
  GrowthNotify(114),
  /**
   * <code>ItemNotify = 115;</code>
   */
  ItemNotify(115),
  /**
   * <code>StageNotify = 116;</code>
   */
  StageNotify(116),
  /**
   * <code>StageBossGaugeOnRequest = 117;</code>
   */
  StageBossGaugeOnRequest(117),
  /**
   * <code>StageBossGaugeOnResponse = 118;</code>
   */
  StageBossGaugeOnResponse(118),
  /**
   * <pre>
   * 119 사용 가능
   * </pre>
   *
   * <code>ViewExplorationNotify = 120;</code>
   */
  ViewExplorationNotify(120),
  /**
   * <code>ExplorationStartRequest = 121;</code>
   */
  ExplorationStartRequest(121),
  /**
   * <code>ExplorationStartResponse = 122;</code>
   */
  ExplorationStartResponse(122),
  /**
   * <code>ExplorationEndRequest = 123;</code>
   */
  ExplorationEndRequest(123),
  /**
   * <code>ExplorationEndResponse = 124;</code>
   */
  ExplorationEndResponse(124),
  /**
   * <code>ExplorationChangeRequest = 125;</code>
   */
  ExplorationChangeRequest(125),
  /**
   * <code>ExplorationChangeResponse = 126;</code>
   */
  ExplorationChangeResponse(126),
  /**
   * <code>ViewExplorationCommercialRequest = 127;</code>
   */
  ViewExplorationCommercialRequest(127),
  /**
   * <code>ViewExplorationCommercialResponse = 128;</code>
   */
  ViewExplorationCommercialResponse(128),
  /**
   * <code>ExplorationCommercialRequest = 129;</code>
   */
  ExplorationCommercialRequest(129),
  /**
   * <code>ExplorationCommercialResponse = 130;</code>
   */
  ExplorationCommercialResponse(130),
  /**
   * <code>ExplorationAccelerationRequest = 131;</code>
   */
  ExplorationAccelerationRequest(131),
  /**
   * <code>ExplorationAccelerationResponse = 132;</code>
   */
  ExplorationAccelerationResponse(132),
  /**
   * <code>ExplorationEditAutoRequest = 133;</code>
   */
  ExplorationEditAutoRequest(133),
  /**
   * <code>ExplorationEditAutoResponse = 134;</code>
   */
  ExplorationEditAutoResponse(134),
  /**
   * <code>CurrencyNotify = 135;</code>
   */
  CurrencyNotify(135),
  /**
   * <code>AttackPowerRankRequest = 136;</code>
   */
  AttackPowerRankRequest(136),
  /**
   * <code>AttackPowerRankResponse = 137;</code>
   */
  AttackPowerRankResponse(137),
  /**
   * <code>GetPlayerDetailInfoRequest = 138;</code>
   */
  GetPlayerDetailInfoRequest(138),
  /**
   * <code>GetPlayerDetailInfoResponse = 139;</code>
   */
  GetPlayerDetailInfoResponse(139),
  /**
   * <code>PlayerSpawnGachaRequest = 140;</code>
   */
  PlayerSpawnGachaRequest(140),
  /**
   * <code>PlayerSpawnGachaResponse = 141;</code>
   */
  PlayerSpawnGachaResponse(141),
  /**
   * <code>PlayerPickUpGachaRewardRequest = 142;</code>
   */
  PlayerPickUpGachaRewardRequest(142),
  /**
   * <code>PlayerPickUpGachaRewardResponse = 143;</code>
   */
  PlayerPickUpGachaRewardResponse(143),
  /**
   * <code>PlayerViewGachaCommercialRequest = 144;</code>
   */
  PlayerViewGachaCommercialRequest(144),
  /**
   * <code>PlayerViewGachaCommercialResponse = 145;</code>
   */
  PlayerViewGachaCommercialResponse(145),
  /**
   * <code>PlayerConditionPackageInfoRequest = 146;</code>
   */
  PlayerConditionPackageInfoRequest(146),
  /**
   * <code>PlayerConditionPackageInfoResponse = 147;</code>
   */
  PlayerConditionPackageInfoResponse(147),
  /**
   * <code>PlayerConditionPackageNotify = 148;</code>
   */
  PlayerConditionPackageNotify(148),
  /**
   * <code>DiggingRequest = 150;</code>
   */
  DiggingRequest(150),
  /**
   * <code>DiggingResponse = 151;</code>
   */
  DiggingResponse(151),
  /**
   * <code>DiggingUpgradeRequest = 152;</code>
   */
  DiggingUpgradeRequest(152),
  /**
   * <code>DiggingUpgradeResponse = 153;</code>
   */
  DiggingUpgradeResponse(153),
  /**
   * <code>DiggingUpgradeInfoRequest = 154;</code>
   */
  DiggingUpgradeInfoRequest(154),
  /**
   * <code>DiggingUpgradeInfoResponse = 155;</code>
   */
  DiggingUpgradeInfoResponse(155),
  /**
   * <code>DiggingCompleteRequest = 156;</code>
   */
  DiggingCompleteRequest(156),
  /**
   * <code>DiggingCompleteResponse = 157;</code>
   */
  DiggingCompleteResponse(157),
  /**
   * <code>ViewDiggingCommercialRequest = 158;</code>
   */
  ViewDiggingCommercialRequest(158),
  /**
   * <code>ViewDiggingCommercialResponse = 159;</code>
   */
  ViewDiggingCommercialResponse(159),
  /**
   * <code>UseAcceleratorRequest = 160;</code>
   */
  UseAcceleratorRequest(160),
  /**
   * <code>UseAcceleratorResponse = 161;</code>
   */
  UseAcceleratorResponse(161),
  /**
   * <code>DiggingInfoRequest = 162;</code>
   */
  DiggingInfoRequest(162),
  /**
   * <code>DiggingInfoResponse = 163;</code>
   */
  DiggingInfoResponse(163),
  /**
   * <code>UseMultiAcceleratorRequest = 164;</code>
   */
  UseMultiAcceleratorRequest(164),
  /**
   * <code>UseMultiAcceleratorResponse = 165;</code>
   */
  UseMultiAcceleratorResponse(165),
  /**
   * <code>PlayerGachaInfoRequest = 166;</code>
   */
  PlayerGachaInfoRequest(166),
  /**
   * <code>PlayerGachaInfoResponse = 167;</code>
   */
  PlayerGachaInfoResponse(167),
  /**
   * <code>PlayerShopItemInfoRequest = 168;</code>
   */
  PlayerShopItemInfoRequest(168),
  /**
   * <code>PlayerShopItemInfoResponse = 169;</code>
   */
  PlayerShopItemInfoResponse(169),
  /**
   * <code>PlayerPurchaseShopItemRequest = 172;</code>
   */
  PlayerPurchaseShopItemRequest(172),
  /**
   * <code>PlayerPurchaseShopItemResponse = 173;</code>
   */
  PlayerPurchaseShopItemResponse(173),
  /**
   * <code>PlayerShopPassInfoRequest = 174;</code>
   */
  PlayerShopPassInfoRequest(174),
  /**
   * <code>PlayerShopPassInfoResponse = 175;</code>
   */
  PlayerShopPassInfoResponse(175),
  /**
   * <code>PlayerShopPassRewardRequest = 176;</code>
   */
  PlayerShopPassRewardRequest(176),
  /**
   * <code>PlayerShopPassRewardResponse = 177;</code>
   */
  PlayerShopPassRewardResponse(177),
  /**
   * <code>AttackPowerRankNotify = 179;</code>
   */
  AttackPowerRankNotify(179),
  /**
   * <code>DuelRequest = 180;</code>
   */
  DuelRequest(180),
  /**
   * <code>DuelResponse = 181;</code>
   */
  DuelResponse(181),
  /**
   * <code>FarmInfoRequest = 200;</code>
   */
  FarmInfoRequest(200),
  /**
   * <code>FarmInfoResponse = 201;</code>
   */
  FarmInfoResponse(201),
  /**
   * <code>FarmPlantSeedRequest = 202;</code>
   */
  FarmPlantSeedRequest(202),
  /**
   * <code>FarmPlantSeedResponse = 203;</code>
   */
  FarmPlantSeedResponse(203),
  /**
   * <code>FarmPlantBoostRequest = 204;</code>
   */
  FarmPlantBoostRequest(204),
  /**
   * <code>FarmPlantBoostResponse = 205;</code>
   */
  FarmPlantBoostResponse(205),
  /**
   * <code>FarmPlantHarvestRequest = 206;</code>
   */
  FarmPlantHarvestRequest(206),
  /**
   * <code>FarmPlantHarvestResponse = 207;</code>
   */
  FarmPlantHarvestResponse(207),
  /**
   * <code>FarmStealRequest = 208;</code>
   */
  FarmStealRequest(208),
  /**
   * <code>FarmStealResponse = 209;</code>
   */
  FarmStealResponse(209),
  /**
   * <code>FarmReturnStolenPlantsToThiefRequest = 210;</code>
   */
  FarmReturnStolenPlantsToThiefRequest(210),
  /**
   * <code>FarmReturnStolenPlantsToThiefResponse = 211;</code>
   */
  FarmReturnStolenPlantsToThiefResponse(211),
  /**
   * <code>FarmRemoveThiefByBattleRequest = 212;</code>
   */
  FarmRemoveThiefByBattleRequest(212),
  /**
   * <code>FarmRemoveThiefByBattleResponse = 213;</code>
   */
  FarmRemoveThiefByBattleResponse(213),
  /**
   * <code>FarmHistoryListRequest = 214;</code>
   */
  FarmHistoryListRequest(214),
  /**
   * <code>FarmHistoryListResponse = 215;</code>
   */
  FarmHistoryListResponse(215),
  /**
   * <code>FarmFriendListRequest = 216;</code>
   */
  FarmFriendListRequest(216),
  /**
   * <code>FarmFriendListResponse = 217;</code>
   */
  FarmFriendListResponse(217),
  /**
   * <code>FarmOtherListRequest = 218;</code>
   */
  FarmOtherListRequest(218),
  /**
   * <code>FarmOtherListResponse = 219;</code>
   */
  FarmOtherListResponse(219),
  /**
   * <code>FarmCommercialInfoRequest = 220;</code>
   */
  FarmCommercialInfoRequest(220),
  /**
   * <code>FarmCommercialInfoResponse = 221;</code>
   */
  FarmCommercialInfoResponse(221),
  /**
   * <code>FarmCommercialSeedViewRequest = 222;</code>
   */
  FarmCommercialSeedViewRequest(222),
  /**
   * <code>FarmCommercialSeedViewResponse = 223;</code>
   */
  FarmCommercialSeedViewResponse(223),
  /**
   * <code>FarmCookInfoRequest = 224;</code>
   */
  FarmCookInfoRequest(224),
  /**
   * <code>FarmCookInfoResponse = 225;</code>
   */
  FarmCookInfoResponse(225),
  /**
   * <code>FarmCookRequest = 226;</code>
   */
  FarmCookRequest(226),
  /**
   * <code>FarmCookResponse = 227;</code>
   */
  FarmCookResponse(227),
  /**
   * <code>FarmCookCommercialViewRequest = 228;</code>
   */
  FarmCookCommercialViewRequest(228),
  /**
   * <code>FarmCookCommercialViewResponse = 229;</code>
   */
  FarmCookCommercialViewResponse(229),
  /**
   * <code>PortraitNotify = 230;</code>
   */
  PortraitNotify(230),
  /**
   * <code>FarmMyRestrictionsInfoRequest = 231;</code>
   */
  FarmMyRestrictionsInfoRequest(231),
  /**
   * <code>FarmMyRestrictionsInfoResponse = 232;</code>
   */
  FarmMyRestrictionsInfoResponse(232),
  /**
   * <code>FarmChangeNotify = 233;</code>
   */
  FarmChangeNotify(233),
  /**
   * <code>WorldEventRequest = 234;</code>
   */
  WorldEventRequest(234),
  /**
   * <code>WorldEventResponse = 235;</code>
   */
  WorldEventResponse(235),
  /**
   * <code>WorldEventNotify = 236;</code>
   */
  WorldEventNotify(236),
  /**
   * <code>PlayerEventRequest = 237;</code>
   */
  PlayerEventRequest(237),
  /**
   * <code>PlayerEventResponse = 238;</code>
   */
  PlayerEventResponse(238),
  /**
   * <code>PlayerEventRewardRequest = 239;</code>
   */
  PlayerEventRewardRequest(239),
  /**
   * <code>PlayerEventRewardResponse = 240;</code>
   */
  PlayerEventRewardResponse(240),
  /**
   * <code>PlayerEventNotify = 241;</code>
   */
  PlayerEventNotify(241),
  /**
   * <code>PlayerDailyContentRequest = 242;</code>
   */
  PlayerDailyContentRequest(242),
  /**
   * <code>PlayerDailyContentResponse = 243;</code>
   */
  PlayerDailyContentResponse(243),
  /**
   * <code>PlayerDailyContentRewardRequest = 244;</code>
   */
  PlayerDailyContentRewardRequest(244),
  /**
   * <code>PlayerDailyContentRewardResponse = 245;</code>
   */
  PlayerDailyContentRewardResponse(245),
  /**
   * <code>PlayerDailyContentNotify = 246;</code>
   */
  PlayerDailyContentNotify(246),
  /**
   * <code>PlayerAchievementRequest = 247;</code>
   */
  PlayerAchievementRequest(247),
  /**
   * <code>PlayerAchievementResponse = 248;</code>
   */
  PlayerAchievementResponse(248),
  /**
   * <code>PlayerAchievementNotify = 249;</code>
   */
  PlayerAchievementNotify(249),
  /**
   * <code>PlayerAchievementRewardRequest = 250;</code>
   */
  PlayerAchievementRewardRequest(250),
  /**
   * <code>PlayerAchievementRewardResponse = 251;</code>
   */
  PlayerAchievementRewardResponse(251),
  /**
   * <code>PlayerQuestRequest = 252;</code>
   */
  PlayerQuestRequest(252),
  /**
   * <code>PlayerQuestResponse = 253;</code>
   */
  PlayerQuestResponse(253),
  /**
   * <code>PlayerQuestRewardRequest = 254;</code>
   */
  PlayerQuestRewardRequest(254),
  /**
   * <code>PlayerQuestRewardResponse = 255;</code>
   */
  PlayerQuestRewardResponse(255),
  /**
   * <code>PlayerQuestNotify = 256;</code>
   */
  PlayerQuestNotify(256),
  /**
   * <code>PlayerDuelHistorySaveRequest = 257;</code>
   */
  PlayerDuelHistorySaveRequest(257),
  /**
   * <code>PlayerDuelHistorySaveResponse = 258;</code>
   */
  PlayerDuelHistorySaveResponse(258),
  /**
   * <code>PlayerDuelHistoriesRequest = 259;</code>
   */
  PlayerDuelHistoriesRequest(259),
  /**
   * <code>PlayerDuelHistoriesResponse = 260;</code>
   */
  PlayerDuelHistoriesResponse(260),
  /**
   * <code>ClanJoinRequestListRequest = 261;</code>
   */
  ClanJoinRequestListRequest(261),
  /**
   * <code>ClanJoinRequestListResponse = 262;</code>
   */
  ClanJoinRequestListResponse(262),
  /**
   * <code>ClanJoinRequestReplyRequest = 263;</code>
   */
  ClanJoinRequestReplyRequest(263),
  /**
   * <code>ClanJoinRequestReplyResponse = 264;</code>
   */
  ClanJoinRequestReplyResponse(264),
  /**
   * <code>ClanJoinRequestReplyNotify = 265;</code>
   */
  ClanJoinRequestReplyNotify(265),
  /**
   * <code>AddFriendResponseRequest = 266;</code>
   */
  AddFriendResponseRequest(266),
  /**
   * <code>AddFriendResponseResponse = 267;</code>
   */
  AddFriendResponseResponse(267),
  /**
   * <code>CreateClanRequest = 270;</code>
   */
  CreateClanRequest(270),
  /**
   * <code>CreateClanResponse = 271;</code>
   */
  CreateClanResponse(271),
  /**
   * <code>ClanInfoRequest = 272;</code>
   */
  ClanInfoRequest(272),
  /**
   * <code>ClanInfoResponse = 273;</code>
   */
  ClanInfoResponse(273),
  /**
   * <code>PlayerClanJoinRequestListRequest = 274;</code>
   */
  PlayerClanJoinRequestListRequest(274),
  /**
   * <code>PlayerClanJoinRequestListResponse = 275;</code>
   */
  PlayerClanJoinRequestListResponse(275),
  /**
   * <code>PlayerClanJoinRequest = 276;</code>
   */
  PlayerClanJoinRequest(276),
  /**
   * <code>PlayerClanJoinResponse = 277;</code>
   */
  PlayerClanJoinResponse(277),
  /**
   * <code>PlayerClanJoinNotify = 278;</code>
   */
  PlayerClanJoinNotify(278),
  /**
   * <code>ClanMemberListRequest = 279;</code>
   */
  ClanMemberListRequest(279),
  /**
   * <code>ClanMemberListResponse = 280;</code>
   */
  ClanMemberListResponse(280),
  /**
   * <code>GetClanRecommendListRequest = 281;</code>
   */
  GetClanRecommendListRequest(281),
  /**
   * <code>GetClanRecommendListResponse = 282;</code>
   */
  GetClanRecommendListResponse(282),
  /**
   * <code>ClanNoticeChangeRequest = 283;</code>
   */
  ClanNoticeChangeRequest(283),
  /**
   * <code>ClanNoticeChangeResponse = 284;</code>
   */
  ClanNoticeChangeResponse(284),
  /**
   * <code>ClanIntroductionChangeRequest = 285;</code>
   */
  ClanIntroductionChangeRequest(285),
  /**
   * <code>ClanIntroductionChangeResponse = 286;</code>
   */
  ClanIntroductionChangeResponse(286),
  /**
   * <code>ClanMemberRoleChangeRequest = 287;</code>
   */
  ClanMemberRoleChangeRequest(287),
  /**
   * <code>ClanMemberRoleChangeResponse = 288;</code>
   */
  ClanMemberRoleChangeResponse(288),
  /**
   * <code>ClanMemberRoleChangeNotify = 289;</code>
   */
  ClanMemberRoleChangeNotify(289),
  /**
   * <code>ClanMemberExpulsionRequest = 290;</code>
   */
  ClanMemberExpulsionRequest(290),
  /**
   * <code>ClanMemberExpulsionResponse = 291;</code>
   */
  ClanMemberExpulsionResponse(291),
  /**
   * <code>ClanMemberLeaveNotify = 292;</code>
   */
  ClanMemberLeaveNotify(292),
  /**
   * <code>ClanMemberExpulsionNotify = 293;</code>
   */
  ClanMemberExpulsionNotify(293),
  /**
   * <code>ClanMemberLeaveRequest = 294;</code>
   */
  ClanMemberLeaveRequest(294),
  /**
   * <code>ClanMemberLeaveResponse = 295;</code>
   */
  ClanMemberLeaveResponse(295),
  /**
   * <code>ClanNameChangeRequest = 296;</code>
   */
  ClanNameChangeRequest(296),
  /**
   * <code>ClanNameChangeResponse = 297;</code>
   */
  ClanNameChangeResponse(297),
  /**
   * <code>PlayerDonateClanRequest = 298;</code>
   */
  PlayerDonateClanRequest(298),
  /**
   * <code>PlayerDonateClanResponse = 299;</code>
   */
  PlayerDonateClanResponse(299),
  /**
   * <code>StoneStatueInfoRequest = 300;</code>
   */
  StoneStatueInfoRequest(300),
  /**
   * <code>StoneStatueInfoResponse = 301;</code>
   */
  StoneStatueInfoResponse(301),
  /**
   * <code>StoneStatueEnchantSlotLockRequest = 302;</code>
   */
  StoneStatueEnchantSlotLockRequest(302),
  /**
   * <code>StoneStatueEnchantSlotLockResponse = 303;</code>
   */
  StoneStatueEnchantSlotLockResponse(303),
  /**
   * <code>StoneStatueEnchantChangeSafeGradeRequest = 304;</code>
   */
  StoneStatueEnchantChangeSafeGradeRequest(304),
  /**
   * <code>StoneStatueEnchantChangeSafeGradeResponse = 305;</code>
   */
  StoneStatueEnchantChangeSafeGradeResponse(305),
  /**
   * <code>StoneStatueEnchantRequest = 306;</code>
   */
  StoneStatueEnchantRequest(306),
  /**
   * <code>StoneStatueEnchantResponse = 307;</code>
   */
  StoneStatueEnchantResponse(307),
  /**
   * <code>StoneStatueGemLevelUpRequest = 308;</code>
   */
  StoneStatueGemLevelUpRequest(308),
  /**
   * <code>StoneStatueGemLevelUpResponse = 309;</code>
   */
  StoneStatueGemLevelUpResponse(309),
  /**
   * <code>StoneStatueGemLimitLevelUpRequest = 310;</code>
   */
  StoneStatueGemLimitLevelUpRequest(310),
  /**
   * <code>StoneStatueGemLimitLevelUpResponse = 311;</code>
   */
  StoneStatueGemLimitLevelUpResponse(311),
  /**
   * <code>StoneStatueAvatarEquipRequest = 312;</code>
   */
  StoneStatueAvatarEquipRequest(312),
  /**
   * <code>StoneStatueAvatarEquipResponse = 313;</code>
   */
  StoneStatueAvatarEquipResponse(313),
  /**
   * <code>PlayerAdvertiseInfoRequest = 314;</code>
   */
  PlayerAdvertiseInfoRequest(314),
  /**
   * <code>PlayerAdvertiseInfoResponse = 315;</code>
   */
  PlayerAdvertiseInfoResponse(315),
  /**
   * <code>PlayerClanDissolutionRequest = 316;</code>
   */
  PlayerClanDissolutionRequest(316),
  /**
   * <code>PlayerClanDissolutionResponse = 317;</code>
   */
  PlayerClanDissolutionResponse(317),
  /**
   * <code>PlayerBlockFriendWithCodeRequest = 318;</code>
   */
  PlayerBlockFriendWithCodeRequest(318),
  /**
   * <code>PlayerBlockFriendWithCodeResponse = 319;</code>
   */
  PlayerBlockFriendWithCodeResponse(319),
  /**
   * <code>ChatNotify = 1000;</code>
   */
  ChatNotify(1000),
  /**
   * <code>ChatHistoryNotify = 1001;</code>
   */
  ChatHistoryNotify(1001),
  /**
   * <code>ChatRequest = 1002;</code>
   */
  ChatRequest(1002),
  /**
   * <code>ChatResponse = 1003;</code>
   */
  ChatResponse(1003),
  /**
   * <code>WhisperRequest = 1004;</code>
   */
  WhisperRequest(1004),
  /**
   * <code>WhisperResponse = 1005;</code>
   */
  WhisperResponse(1005),
  /**
   * <code>ChatHistoriesRequest = 1006;</code>
   */
  ChatHistoriesRequest(1006),
  /**
   * <code>ChatHistoriesResponse = 1007;</code>
   */
  ChatHistoriesResponse(1007),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Ping = 0;</code>
   */
  public static final int Ping_VALUE = 0;
  /**
   * <code>LoginRequest = 1;</code>
   */
  public static final int LoginRequest_VALUE = 1;
  /**
   * <code>LoginResponse = 2;</code>
   */
  public static final int LoginResponse_VALUE = 2;
  /**
   * <code>ChangeEquipAvatarRequest = 3;</code>
   */
  public static final int ChangeEquipAvatarRequest_VALUE = 3;
  /**
   * <code>ChangeEquipAvatarResponse = 4;</code>
   */
  public static final int ChangeEquipAvatarResponse_VALUE = 4;
  /**
   * <code>GrowthLevelUpRequest = 5;</code>
   */
  public static final int GrowthLevelUpRequest_VALUE = 5;
  /**
   * <code>GrowthLevelUpResponse = 6;</code>
   */
  public static final int GrowthLevelUpResponse_VALUE = 6;
  /**
   * <code>GrowthPromoteRequest = 7;</code>
   */
  public static final int GrowthPromoteRequest_VALUE = 7;
  /**
   * <code>GrowthPromoteResponse = 8;</code>
   */
  public static final int GrowthPromoteResponse_VALUE = 8;
  /**
   * <code>GrowthLimitBreakRequest = 9;</code>
   */
  public static final int GrowthLimitBreakRequest_VALUE = 9;
  /**
   * <code>GrowthLimitBreakResponse = 10;</code>
   */
  public static final int GrowthLimitBreakResponse_VALUE = 10;
  /**
   * <code>PartsSlotLevelUpRequest = 11;</code>
   */
  public static final int PartsSlotLevelUpRequest_VALUE = 11;
  /**
   * <code>PartsSlotLevelUpResponse = 12;</code>
   */
  public static final int PartsSlotLevelUpResponse_VALUE = 12;
  /**
   * <code>GrowthEquipPartsRequest = 13;</code>
   */
  public static final int GrowthEquipPartsRequest_VALUE = 13;
  /**
   * <code>GrowthEquipPartsResponse = 14;</code>
   */
  public static final int GrowthEquipPartsResponse_VALUE = 14;
  /**
   * <code>LogoutRequest = 15;</code>
   */
  public static final int LogoutRequest_VALUE = 15;
  /**
   * <code>LogoutResponse = 16;</code>
   */
  public static final int LogoutResponse_VALUE = 16;
  /**
   * <code>LogoutNotify = 17;</code>
   */
  public static final int LogoutNotify_VALUE = 17;
  /**
   * <code>MailRequest = 18;</code>
   */
  public static final int MailRequest_VALUE = 18;
  /**
   * <code>MailResponse = 19;</code>
   */
  public static final int MailResponse_VALUE = 19;
  /**
   * <code>MailReadRequest = 20;</code>
   */
  public static final int MailReadRequest_VALUE = 20;
  /**
   * <code>MailReadResponse = 21;</code>
   */
  public static final int MailReadResponse_VALUE = 21;
  /**
   * <code>MailNotify = 22;</code>
   */
  public static final int MailNotify_VALUE = 22;
  /**
   * <code>CollectionLevelUpRequest = 23;</code>
   */
  public static final int CollectionLevelUpRequest_VALUE = 23;
  /**
   * <code>CollectionLevelUpResponse = 24;</code>
   */
  public static final int CollectionLevelUpResponse_VALUE = 24;
  /**
   * <code>CollectionRequest = 25;</code>
   */
  public static final int CollectionRequest_VALUE = 25;
  /**
   * <code>CollectionResponse = 26;</code>
   */
  public static final int CollectionResponse_VALUE = 26;
  /**
   * <code>SyncItemCountRequest = 27;</code>
   */
  public static final int SyncItemCountRequest_VALUE = 27;
  /**
   * <code>SyncItemCountResponse = 28;</code>
   */
  public static final int SyncItemCountResponse_VALUE = 28;
  /**
   * <code>PartsSlotRequest = 29;</code>
   */
  public static final int PartsSlotRequest_VALUE = 29;
  /**
   * <code>PartsSlotResponse = 30;</code>
   */
  public static final int PartsSlotResponse_VALUE = 30;
  /**
   * <code>StageClearSaveRequest = 31;</code>
   */
  public static final int StageClearSaveRequest_VALUE = 31;
  /**
   * <code>StageClearSaveResponse = 32;</code>
   */
  public static final int StageClearSaveResponse_VALUE = 32;
  /**
   * <code>ChangePortraitIconRequest = 33;</code>
   */
  public static final int ChangePortraitIconRequest_VALUE = 33;
  /**
   * <code>ChangePortraitIconResponse = 34;</code>
   */
  public static final int ChangePortraitIconResponse_VALUE = 34;
  /**
   * <code>ChangePlayerNameRequest = 35;</code>
   */
  public static final int ChangePlayerNameRequest_VALUE = 35;
  /**
   * <code>ChangePlayerNameResponse = 36;</code>
   */
  public static final int ChangePlayerNameResponse_VALUE = 36;
  /**
   * <code>StatsRequest = 37;</code>
   */
  public static final int StatsRequest_VALUE = 37;
  /**
   * <code>StatsResponse = 38;</code>
   */
  public static final int StatsResponse_VALUE = 38;
  /**
   * <code>CharacterStatGrowthRequest = 39;</code>
   */
  public static final int CharacterStatGrowthRequest_VALUE = 39;
  /**
   * <code>CharacterStatGrowthResponse = 40;</code>
   */
  public static final int CharacterStatGrowthResponse_VALUE = 40;
  /**
   * <code>CharacterStatGrowthLevelUpRequest = 41;</code>
   */
  public static final int CharacterStatGrowthLevelUpRequest_VALUE = 41;
  /**
   * <code>CharacterStatGrowthLevelUpResponse = 42;</code>
   */
  public static final int CharacterStatGrowthLevelUpResponse_VALUE = 42;
  /**
   * <code>EquipPresetRequest = 43;</code>
   */
  public static final int EquipPresetRequest_VALUE = 43;
  /**
   * <code>EquipPresetResponse = 44;</code>
   */
  public static final int EquipPresetResponse_VALUE = 44;
  /**
   * <code>EquipPresetEquipRequest = 45;</code>
   */
  public static final int EquipPresetEquipRequest_VALUE = 45;
  /**
   * <code>EquipPresetEquipResponse = 46;</code>
   */
  public static final int EquipPresetEquipResponse_VALUE = 46;
  /**
   * <code>EquipPresetUnEquipRequest = 47;</code>
   */
  public static final int EquipPresetUnEquipRequest_VALUE = 47;
  /**
   * <code>EquipPresetUnEquipResponse = 48;</code>
   */
  public static final int EquipPresetUnEquipResponse_VALUE = 48;
  /**
   * <code>EquipPresetNameChangeRequest = 51;</code>
   */
  public static final int EquipPresetNameChangeRequest_VALUE = 51;
  /**
   * <code>EquipPresetNameChangeResponse = 52;</code>
   */
  public static final int EquipPresetNameChangeResponse_VALUE = 52;
  /**
   * <code>EquipPresetIndexChangeRequest = 53;</code>
   */
  public static final int EquipPresetIndexChangeRequest_VALUE = 53;
  /**
   * <code>EquipPresetIndexChangeResponse = 54;</code>
   */
  public static final int EquipPresetIndexChangeResponse_VALUE = 54;
  /**
   * <code>StatsNotify = 55;</code>
   */
  public static final int StatsNotify_VALUE = 55;
  /**
   * <code>PlayerLevelUpNotify = 56;</code>
   */
  public static final int PlayerLevelUpNotify_VALUE = 56;
  /**
   * <code>DailyDungeonStartRequest = 57;</code>
   */
  public static final int DailyDungeonStartRequest_VALUE = 57;
  /**
   * <code>DailyDungeonStartResponse = 58;</code>
   */
  public static final int DailyDungeonStartResponse_VALUE = 58;
  /**
   * <code>DailyDungeonClearRequest = 59;</code>
   */
  public static final int DailyDungeonClearRequest_VALUE = 59;
  /**
   * <code>DailyDungeonClearResponse = 60;</code>
   */
  public static final int DailyDungeonClearResponse_VALUE = 60;
  /**
   * <code>DailyDungeonRequest = 61;</code>
   */
  public static final int DailyDungeonRequest_VALUE = 61;
  /**
   * <code>DailyDungeonResponse = 62;</code>
   */
  public static final int DailyDungeonResponse_VALUE = 62;
  /**
   * <code>DailyDungeonViewAdvertiseRequest = 63;</code>
   */
  public static final int DailyDungeonViewAdvertiseRequest_VALUE = 63;
  /**
   * <code>DailyDungeonViewAdvertiseResponse = 64;</code>
   */
  public static final int DailyDungeonViewAdvertiseResponse_VALUE = 64;
  /**
   * <code>RaidDungeonStartRequest = 65;</code>
   */
  public static final int RaidDungeonStartRequest_VALUE = 65;
  /**
   * <code>RaidDungeonStartResponse = 66;</code>
   */
  public static final int RaidDungeonStartResponse_VALUE = 66;
  /**
   * <code>RaidDungeonClearRequest = 67;</code>
   */
  public static final int RaidDungeonClearRequest_VALUE = 67;
  /**
   * <code>RaidDungeonClearResponse = 68;</code>
   */
  public static final int RaidDungeonClearResponse_VALUE = 68;
  /**
   * <code>RaidDungeonRequest = 69;</code>
   */
  public static final int RaidDungeonRequest_VALUE = 69;
  /**
   * <code>RaidDungeonResponse = 70;</code>
   */
  public static final int RaidDungeonResponse_VALUE = 70;
  /**
   * <code>RaidDungeonViewAdvertiseRequest = 71;</code>
   */
  public static final int RaidDungeonViewAdvertiseRequest_VALUE = 71;
  /**
   * <code>RaidDungeonViewAdvertiseResponse = 72;</code>
   */
  public static final int RaidDungeonViewAdvertiseResponse_VALUE = 72;
  /**
   * <code>TowerStartRequest = 73;</code>
   */
  public static final int TowerStartRequest_VALUE = 73;
  /**
   * <code>TowerStartResponse = 74;</code>
   */
  public static final int TowerStartResponse_VALUE = 74;
  /**
   * <code>TowerClearRequest = 75;</code>
   */
  public static final int TowerClearRequest_VALUE = 75;
  /**
   * <code>TowerClearResponse = 76;</code>
   */
  public static final int TowerClearResponse_VALUE = 76;
  /**
   * <code>TowerRequest = 77;</code>
   */
  public static final int TowerRequest_VALUE = 77;
  /**
   * <code>TowerResponse = 78;</code>
   */
  public static final int TowerResponse_VALUE = 78;
  /**
   * <code>CooperativeRaidDungeonRequest = 79;</code>
   */
  public static final int CooperativeRaidDungeonRequest_VALUE = 79;
  /**
   * <code>CooperativeRaidDungeonResponse = 80;</code>
   */
  public static final int CooperativeRaidDungeonResponse_VALUE = 80;
  /**
   * <code>CompetitiveRaidDungeonRequest = 81;</code>
   */
  public static final int CompetitiveRaidDungeonRequest_VALUE = 81;
  /**
   * <code>CompetitiveRaidDungeonResponse = 82;</code>
   */
  public static final int CompetitiveRaidDungeonResponse_VALUE = 82;
  /**
   * <code>CompetitiveRaidDungeonRankRequest = 83;</code>
   */
  public static final int CompetitiveRaidDungeonRankRequest_VALUE = 83;
  /**
   * <code>CompetitiveRaidDungeonRankResponse = 84;</code>
   */
  public static final int CompetitiveRaidDungeonRankResponse_VALUE = 84;
  /**
   * <code>FriendListRequest = 85;</code>
   */
  public static final int FriendListRequest_VALUE = 85;
  /**
   * <code>FriendListResponse = 86;</code>
   */
  public static final int FriendListResponse_VALUE = 86;
  /**
   * <code>AddFriendRequest = 87;</code>
   */
  public static final int AddFriendRequest_VALUE = 87;
  /**
   * <code>AddFriendResponse = 88;</code>
   */
  public static final int AddFriendResponse_VALUE = 88;
  /**
   * <code>DeleteFriendRequest = 89;</code>
   */
  public static final int DeleteFriendRequest_VALUE = 89;
  /**
   * <code>DeleteFriendResponse = 90;</code>
   */
  public static final int DeleteFriendResponse_VALUE = 90;
  /**
   * <code>GiveFriendGiftRequest = 91;</code>
   */
  public static final int GiveFriendGiftRequest_VALUE = 91;
  /**
   * <code>GiveFriendGiftResponse = 92;</code>
   */
  public static final int GiveFriendGiftResponse_VALUE = 92;
  /**
   * <code>SearchFriendRequest = 93;</code>
   */
  public static final int SearchFriendRequest_VALUE = 93;
  /**
   * <code>SearchFriendResponse = 94;</code>
   */
  public static final int SearchFriendResponse_VALUE = 94;
  /**
   * <code>AddFriendCancelRequest = 95;</code>
   */
  public static final int AddFriendCancelRequest_VALUE = 95;
  /**
   * <code>AddFriendCancelResponse = 96;</code>
   */
  public static final int AddFriendCancelResponse_VALUE = 96;
  /**
   * <code>RecommendFriendRequest = 98;</code>
   */
  public static final int RecommendFriendRequest_VALUE = 98;
  /**
   * <code>RecommendFriendResponse = 99;</code>
   */
  public static final int RecommendFriendResponse_VALUE = 99;
  /**
   * <code>AddFriendNotify = 100;</code>
   */
  public static final int AddFriendNotify_VALUE = 100;
  /**
   * <code>DeleteFriendNotify = 101;</code>
   */
  public static final int DeleteFriendNotify_VALUE = 101;
  /**
   * <code>ChangeFriendStateNotify = 102;</code>
   */
  public static final int ChangeFriendStateNotify_VALUE = 102;
  /**
   * <code>BlockPlayerRequest = 103;</code>
   */
  public static final int BlockPlayerRequest_VALUE = 103;
  /**
   * <code>BlockPlayerResponse = 104;</code>
   */
  public static final int BlockPlayerResponse_VALUE = 104;
  /**
   * <code>UnBlockPlayerRequest = 105;</code>
   */
  public static final int UnBlockPlayerRequest_VALUE = 105;
  /**
   * <code>UnBlockPlayerResponse = 106;</code>
   */
  public static final int UnBlockPlayerResponse_VALUE = 106;
  /**
   * <code>PlayerBlockListRequest = 107;</code>
   */
  public static final int PlayerBlockListRequest_VALUE = 107;
  /**
   * <code>PlayerBlockListResponse = 108;</code>
   */
  public static final int PlayerBlockListResponse_VALUE = 108;
  /**
   * <code>CheatRequest = 109;</code>
   */
  public static final int CheatRequest_VALUE = 109;
  /**
   * <code>CheatResponse = 110;</code>
   */
  public static final int CheatResponse_VALUE = 110;
  /**
   * <code>ViewAdvertiseRequest = 111;</code>
   */
  public static final int ViewAdvertiseRequest_VALUE = 111;
  /**
   * <code>ViewAdvertiseResponse = 112;</code>
   */
  public static final int ViewAdvertiseResponse_VALUE = 112;
  /**
   * <code>AvatarNotify = 113;</code>
   */
  public static final int AvatarNotify_VALUE = 113;
  /**
   * <code>GrowthNotify = 114;</code>
   */
  public static final int GrowthNotify_VALUE = 114;
  /**
   * <code>ItemNotify = 115;</code>
   */
  public static final int ItemNotify_VALUE = 115;
  /**
   * <code>StageNotify = 116;</code>
   */
  public static final int StageNotify_VALUE = 116;
  /**
   * <code>StageBossGaugeOnRequest = 117;</code>
   */
  public static final int StageBossGaugeOnRequest_VALUE = 117;
  /**
   * <code>StageBossGaugeOnResponse = 118;</code>
   */
  public static final int StageBossGaugeOnResponse_VALUE = 118;
  /**
   * <pre>
   * 119 사용 가능
   * </pre>
   *
   * <code>ViewExplorationNotify = 120;</code>
   */
  public static final int ViewExplorationNotify_VALUE = 120;
  /**
   * <code>ExplorationStartRequest = 121;</code>
   */
  public static final int ExplorationStartRequest_VALUE = 121;
  /**
   * <code>ExplorationStartResponse = 122;</code>
   */
  public static final int ExplorationStartResponse_VALUE = 122;
  /**
   * <code>ExplorationEndRequest = 123;</code>
   */
  public static final int ExplorationEndRequest_VALUE = 123;
  /**
   * <code>ExplorationEndResponse = 124;</code>
   */
  public static final int ExplorationEndResponse_VALUE = 124;
  /**
   * <code>ExplorationChangeRequest = 125;</code>
   */
  public static final int ExplorationChangeRequest_VALUE = 125;
  /**
   * <code>ExplorationChangeResponse = 126;</code>
   */
  public static final int ExplorationChangeResponse_VALUE = 126;
  /**
   * <code>ViewExplorationCommercialRequest = 127;</code>
   */
  public static final int ViewExplorationCommercialRequest_VALUE = 127;
  /**
   * <code>ViewExplorationCommercialResponse = 128;</code>
   */
  public static final int ViewExplorationCommercialResponse_VALUE = 128;
  /**
   * <code>ExplorationCommercialRequest = 129;</code>
   */
  public static final int ExplorationCommercialRequest_VALUE = 129;
  /**
   * <code>ExplorationCommercialResponse = 130;</code>
   */
  public static final int ExplorationCommercialResponse_VALUE = 130;
  /**
   * <code>ExplorationAccelerationRequest = 131;</code>
   */
  public static final int ExplorationAccelerationRequest_VALUE = 131;
  /**
   * <code>ExplorationAccelerationResponse = 132;</code>
   */
  public static final int ExplorationAccelerationResponse_VALUE = 132;
  /**
   * <code>ExplorationEditAutoRequest = 133;</code>
   */
  public static final int ExplorationEditAutoRequest_VALUE = 133;
  /**
   * <code>ExplorationEditAutoResponse = 134;</code>
   */
  public static final int ExplorationEditAutoResponse_VALUE = 134;
  /**
   * <code>CurrencyNotify = 135;</code>
   */
  public static final int CurrencyNotify_VALUE = 135;
  /**
   * <code>AttackPowerRankRequest = 136;</code>
   */
  public static final int AttackPowerRankRequest_VALUE = 136;
  /**
   * <code>AttackPowerRankResponse = 137;</code>
   */
  public static final int AttackPowerRankResponse_VALUE = 137;
  /**
   * <code>GetPlayerDetailInfoRequest = 138;</code>
   */
  public static final int GetPlayerDetailInfoRequest_VALUE = 138;
  /**
   * <code>GetPlayerDetailInfoResponse = 139;</code>
   */
  public static final int GetPlayerDetailInfoResponse_VALUE = 139;
  /**
   * <code>PlayerSpawnGachaRequest = 140;</code>
   */
  public static final int PlayerSpawnGachaRequest_VALUE = 140;
  /**
   * <code>PlayerSpawnGachaResponse = 141;</code>
   */
  public static final int PlayerSpawnGachaResponse_VALUE = 141;
  /**
   * <code>PlayerPickUpGachaRewardRequest = 142;</code>
   */
  public static final int PlayerPickUpGachaRewardRequest_VALUE = 142;
  /**
   * <code>PlayerPickUpGachaRewardResponse = 143;</code>
   */
  public static final int PlayerPickUpGachaRewardResponse_VALUE = 143;
  /**
   * <code>PlayerViewGachaCommercialRequest = 144;</code>
   */
  public static final int PlayerViewGachaCommercialRequest_VALUE = 144;
  /**
   * <code>PlayerViewGachaCommercialResponse = 145;</code>
   */
  public static final int PlayerViewGachaCommercialResponse_VALUE = 145;
  /**
   * <code>PlayerConditionPackageInfoRequest = 146;</code>
   */
  public static final int PlayerConditionPackageInfoRequest_VALUE = 146;
  /**
   * <code>PlayerConditionPackageInfoResponse = 147;</code>
   */
  public static final int PlayerConditionPackageInfoResponse_VALUE = 147;
  /**
   * <code>PlayerConditionPackageNotify = 148;</code>
   */
  public static final int PlayerConditionPackageNotify_VALUE = 148;
  /**
   * <code>DiggingRequest = 150;</code>
   */
  public static final int DiggingRequest_VALUE = 150;
  /**
   * <code>DiggingResponse = 151;</code>
   */
  public static final int DiggingResponse_VALUE = 151;
  /**
   * <code>DiggingUpgradeRequest = 152;</code>
   */
  public static final int DiggingUpgradeRequest_VALUE = 152;
  /**
   * <code>DiggingUpgradeResponse = 153;</code>
   */
  public static final int DiggingUpgradeResponse_VALUE = 153;
  /**
   * <code>DiggingUpgradeInfoRequest = 154;</code>
   */
  public static final int DiggingUpgradeInfoRequest_VALUE = 154;
  /**
   * <code>DiggingUpgradeInfoResponse = 155;</code>
   */
  public static final int DiggingUpgradeInfoResponse_VALUE = 155;
  /**
   * <code>DiggingCompleteRequest = 156;</code>
   */
  public static final int DiggingCompleteRequest_VALUE = 156;
  /**
   * <code>DiggingCompleteResponse = 157;</code>
   */
  public static final int DiggingCompleteResponse_VALUE = 157;
  /**
   * <code>ViewDiggingCommercialRequest = 158;</code>
   */
  public static final int ViewDiggingCommercialRequest_VALUE = 158;
  /**
   * <code>ViewDiggingCommercialResponse = 159;</code>
   */
  public static final int ViewDiggingCommercialResponse_VALUE = 159;
  /**
   * <code>UseAcceleratorRequest = 160;</code>
   */
  public static final int UseAcceleratorRequest_VALUE = 160;
  /**
   * <code>UseAcceleratorResponse = 161;</code>
   */
  public static final int UseAcceleratorResponse_VALUE = 161;
  /**
   * <code>DiggingInfoRequest = 162;</code>
   */
  public static final int DiggingInfoRequest_VALUE = 162;
  /**
   * <code>DiggingInfoResponse = 163;</code>
   */
  public static final int DiggingInfoResponse_VALUE = 163;
  /**
   * <code>UseMultiAcceleratorRequest = 164;</code>
   */
  public static final int UseMultiAcceleratorRequest_VALUE = 164;
  /**
   * <code>UseMultiAcceleratorResponse = 165;</code>
   */
  public static final int UseMultiAcceleratorResponse_VALUE = 165;
  /**
   * <code>PlayerGachaInfoRequest = 166;</code>
   */
  public static final int PlayerGachaInfoRequest_VALUE = 166;
  /**
   * <code>PlayerGachaInfoResponse = 167;</code>
   */
  public static final int PlayerGachaInfoResponse_VALUE = 167;
  /**
   * <code>PlayerShopItemInfoRequest = 168;</code>
   */
  public static final int PlayerShopItemInfoRequest_VALUE = 168;
  /**
   * <code>PlayerShopItemInfoResponse = 169;</code>
   */
  public static final int PlayerShopItemInfoResponse_VALUE = 169;
  /**
   * <code>PlayerPurchaseShopItemRequest = 172;</code>
   */
  public static final int PlayerPurchaseShopItemRequest_VALUE = 172;
  /**
   * <code>PlayerPurchaseShopItemResponse = 173;</code>
   */
  public static final int PlayerPurchaseShopItemResponse_VALUE = 173;
  /**
   * <code>PlayerShopPassInfoRequest = 174;</code>
   */
  public static final int PlayerShopPassInfoRequest_VALUE = 174;
  /**
   * <code>PlayerShopPassInfoResponse = 175;</code>
   */
  public static final int PlayerShopPassInfoResponse_VALUE = 175;
  /**
   * <code>PlayerShopPassRewardRequest = 176;</code>
   */
  public static final int PlayerShopPassRewardRequest_VALUE = 176;
  /**
   * <code>PlayerShopPassRewardResponse = 177;</code>
   */
  public static final int PlayerShopPassRewardResponse_VALUE = 177;
  /**
   * <code>AttackPowerRankNotify = 179;</code>
   */
  public static final int AttackPowerRankNotify_VALUE = 179;
  /**
   * <code>DuelRequest = 180;</code>
   */
  public static final int DuelRequest_VALUE = 180;
  /**
   * <code>DuelResponse = 181;</code>
   */
  public static final int DuelResponse_VALUE = 181;
  /**
   * <code>FarmInfoRequest = 200;</code>
   */
  public static final int FarmInfoRequest_VALUE = 200;
  /**
   * <code>FarmInfoResponse = 201;</code>
   */
  public static final int FarmInfoResponse_VALUE = 201;
  /**
   * <code>FarmPlantSeedRequest = 202;</code>
   */
  public static final int FarmPlantSeedRequest_VALUE = 202;
  /**
   * <code>FarmPlantSeedResponse = 203;</code>
   */
  public static final int FarmPlantSeedResponse_VALUE = 203;
  /**
   * <code>FarmPlantBoostRequest = 204;</code>
   */
  public static final int FarmPlantBoostRequest_VALUE = 204;
  /**
   * <code>FarmPlantBoostResponse = 205;</code>
   */
  public static final int FarmPlantBoostResponse_VALUE = 205;
  /**
   * <code>FarmPlantHarvestRequest = 206;</code>
   */
  public static final int FarmPlantHarvestRequest_VALUE = 206;
  /**
   * <code>FarmPlantHarvestResponse = 207;</code>
   */
  public static final int FarmPlantHarvestResponse_VALUE = 207;
  /**
   * <code>FarmStealRequest = 208;</code>
   */
  public static final int FarmStealRequest_VALUE = 208;
  /**
   * <code>FarmStealResponse = 209;</code>
   */
  public static final int FarmStealResponse_VALUE = 209;
  /**
   * <code>FarmReturnStolenPlantsToThiefRequest = 210;</code>
   */
  public static final int FarmReturnStolenPlantsToThiefRequest_VALUE = 210;
  /**
   * <code>FarmReturnStolenPlantsToThiefResponse = 211;</code>
   */
  public static final int FarmReturnStolenPlantsToThiefResponse_VALUE = 211;
  /**
   * <code>FarmRemoveThiefByBattleRequest = 212;</code>
   */
  public static final int FarmRemoveThiefByBattleRequest_VALUE = 212;
  /**
   * <code>FarmRemoveThiefByBattleResponse = 213;</code>
   */
  public static final int FarmRemoveThiefByBattleResponse_VALUE = 213;
  /**
   * <code>FarmHistoryListRequest = 214;</code>
   */
  public static final int FarmHistoryListRequest_VALUE = 214;
  /**
   * <code>FarmHistoryListResponse = 215;</code>
   */
  public static final int FarmHistoryListResponse_VALUE = 215;
  /**
   * <code>FarmFriendListRequest = 216;</code>
   */
  public static final int FarmFriendListRequest_VALUE = 216;
  /**
   * <code>FarmFriendListResponse = 217;</code>
   */
  public static final int FarmFriendListResponse_VALUE = 217;
  /**
   * <code>FarmOtherListRequest = 218;</code>
   */
  public static final int FarmOtherListRequest_VALUE = 218;
  /**
   * <code>FarmOtherListResponse = 219;</code>
   */
  public static final int FarmOtherListResponse_VALUE = 219;
  /**
   * <code>FarmCommercialInfoRequest = 220;</code>
   */
  public static final int FarmCommercialInfoRequest_VALUE = 220;
  /**
   * <code>FarmCommercialInfoResponse = 221;</code>
   */
  public static final int FarmCommercialInfoResponse_VALUE = 221;
  /**
   * <code>FarmCommercialSeedViewRequest = 222;</code>
   */
  public static final int FarmCommercialSeedViewRequest_VALUE = 222;
  /**
   * <code>FarmCommercialSeedViewResponse = 223;</code>
   */
  public static final int FarmCommercialSeedViewResponse_VALUE = 223;
  /**
   * <code>FarmCookInfoRequest = 224;</code>
   */
  public static final int FarmCookInfoRequest_VALUE = 224;
  /**
   * <code>FarmCookInfoResponse = 225;</code>
   */
  public static final int FarmCookInfoResponse_VALUE = 225;
  /**
   * <code>FarmCookRequest = 226;</code>
   */
  public static final int FarmCookRequest_VALUE = 226;
  /**
   * <code>FarmCookResponse = 227;</code>
   */
  public static final int FarmCookResponse_VALUE = 227;
  /**
   * <code>FarmCookCommercialViewRequest = 228;</code>
   */
  public static final int FarmCookCommercialViewRequest_VALUE = 228;
  /**
   * <code>FarmCookCommercialViewResponse = 229;</code>
   */
  public static final int FarmCookCommercialViewResponse_VALUE = 229;
  /**
   * <code>PortraitNotify = 230;</code>
   */
  public static final int PortraitNotify_VALUE = 230;
  /**
   * <code>FarmMyRestrictionsInfoRequest = 231;</code>
   */
  public static final int FarmMyRestrictionsInfoRequest_VALUE = 231;
  /**
   * <code>FarmMyRestrictionsInfoResponse = 232;</code>
   */
  public static final int FarmMyRestrictionsInfoResponse_VALUE = 232;
  /**
   * <code>FarmChangeNotify = 233;</code>
   */
  public static final int FarmChangeNotify_VALUE = 233;
  /**
   * <code>WorldEventRequest = 234;</code>
   */
  public static final int WorldEventRequest_VALUE = 234;
  /**
   * <code>WorldEventResponse = 235;</code>
   */
  public static final int WorldEventResponse_VALUE = 235;
  /**
   * <code>WorldEventNotify = 236;</code>
   */
  public static final int WorldEventNotify_VALUE = 236;
  /**
   * <code>PlayerEventRequest = 237;</code>
   */
  public static final int PlayerEventRequest_VALUE = 237;
  /**
   * <code>PlayerEventResponse = 238;</code>
   */
  public static final int PlayerEventResponse_VALUE = 238;
  /**
   * <code>PlayerEventRewardRequest = 239;</code>
   */
  public static final int PlayerEventRewardRequest_VALUE = 239;
  /**
   * <code>PlayerEventRewardResponse = 240;</code>
   */
  public static final int PlayerEventRewardResponse_VALUE = 240;
  /**
   * <code>PlayerEventNotify = 241;</code>
   */
  public static final int PlayerEventNotify_VALUE = 241;
  /**
   * <code>PlayerDailyContentRequest = 242;</code>
   */
  public static final int PlayerDailyContentRequest_VALUE = 242;
  /**
   * <code>PlayerDailyContentResponse = 243;</code>
   */
  public static final int PlayerDailyContentResponse_VALUE = 243;
  /**
   * <code>PlayerDailyContentRewardRequest = 244;</code>
   */
  public static final int PlayerDailyContentRewardRequest_VALUE = 244;
  /**
   * <code>PlayerDailyContentRewardResponse = 245;</code>
   */
  public static final int PlayerDailyContentRewardResponse_VALUE = 245;
  /**
   * <code>PlayerDailyContentNotify = 246;</code>
   */
  public static final int PlayerDailyContentNotify_VALUE = 246;
  /**
   * <code>PlayerAchievementRequest = 247;</code>
   */
  public static final int PlayerAchievementRequest_VALUE = 247;
  /**
   * <code>PlayerAchievementResponse = 248;</code>
   */
  public static final int PlayerAchievementResponse_VALUE = 248;
  /**
   * <code>PlayerAchievementNotify = 249;</code>
   */
  public static final int PlayerAchievementNotify_VALUE = 249;
  /**
   * <code>PlayerAchievementRewardRequest = 250;</code>
   */
  public static final int PlayerAchievementRewardRequest_VALUE = 250;
  /**
   * <code>PlayerAchievementRewardResponse = 251;</code>
   */
  public static final int PlayerAchievementRewardResponse_VALUE = 251;
  /**
   * <code>PlayerQuestRequest = 252;</code>
   */
  public static final int PlayerQuestRequest_VALUE = 252;
  /**
   * <code>PlayerQuestResponse = 253;</code>
   */
  public static final int PlayerQuestResponse_VALUE = 253;
  /**
   * <code>PlayerQuestRewardRequest = 254;</code>
   */
  public static final int PlayerQuestRewardRequest_VALUE = 254;
  /**
   * <code>PlayerQuestRewardResponse = 255;</code>
   */
  public static final int PlayerQuestRewardResponse_VALUE = 255;
  /**
   * <code>PlayerQuestNotify = 256;</code>
   */
  public static final int PlayerQuestNotify_VALUE = 256;
  /**
   * <code>PlayerDuelHistorySaveRequest = 257;</code>
   */
  public static final int PlayerDuelHistorySaveRequest_VALUE = 257;
  /**
   * <code>PlayerDuelHistorySaveResponse = 258;</code>
   */
  public static final int PlayerDuelHistorySaveResponse_VALUE = 258;
  /**
   * <code>PlayerDuelHistoriesRequest = 259;</code>
   */
  public static final int PlayerDuelHistoriesRequest_VALUE = 259;
  /**
   * <code>PlayerDuelHistoriesResponse = 260;</code>
   */
  public static final int PlayerDuelHistoriesResponse_VALUE = 260;
  /**
   * <code>ClanJoinRequestListRequest = 261;</code>
   */
  public static final int ClanJoinRequestListRequest_VALUE = 261;
  /**
   * <code>ClanJoinRequestListResponse = 262;</code>
   */
  public static final int ClanJoinRequestListResponse_VALUE = 262;
  /**
   * <code>ClanJoinRequestReplyRequest = 263;</code>
   */
  public static final int ClanJoinRequestReplyRequest_VALUE = 263;
  /**
   * <code>ClanJoinRequestReplyResponse = 264;</code>
   */
  public static final int ClanJoinRequestReplyResponse_VALUE = 264;
  /**
   * <code>ClanJoinRequestReplyNotify = 265;</code>
   */
  public static final int ClanJoinRequestReplyNotify_VALUE = 265;
  /**
   * <code>AddFriendResponseRequest = 266;</code>
   */
  public static final int AddFriendResponseRequest_VALUE = 266;
  /**
   * <code>AddFriendResponseResponse = 267;</code>
   */
  public static final int AddFriendResponseResponse_VALUE = 267;
  /**
   * <code>CreateClanRequest = 270;</code>
   */
  public static final int CreateClanRequest_VALUE = 270;
  /**
   * <code>CreateClanResponse = 271;</code>
   */
  public static final int CreateClanResponse_VALUE = 271;
  /**
   * <code>ClanInfoRequest = 272;</code>
   */
  public static final int ClanInfoRequest_VALUE = 272;
  /**
   * <code>ClanInfoResponse = 273;</code>
   */
  public static final int ClanInfoResponse_VALUE = 273;
  /**
   * <code>PlayerClanJoinRequestListRequest = 274;</code>
   */
  public static final int PlayerClanJoinRequestListRequest_VALUE = 274;
  /**
   * <code>PlayerClanJoinRequestListResponse = 275;</code>
   */
  public static final int PlayerClanJoinRequestListResponse_VALUE = 275;
  /**
   * <code>PlayerClanJoinRequest = 276;</code>
   */
  public static final int PlayerClanJoinRequest_VALUE = 276;
  /**
   * <code>PlayerClanJoinResponse = 277;</code>
   */
  public static final int PlayerClanJoinResponse_VALUE = 277;
  /**
   * <code>PlayerClanJoinNotify = 278;</code>
   */
  public static final int PlayerClanJoinNotify_VALUE = 278;
  /**
   * <code>ClanMemberListRequest = 279;</code>
   */
  public static final int ClanMemberListRequest_VALUE = 279;
  /**
   * <code>ClanMemberListResponse = 280;</code>
   */
  public static final int ClanMemberListResponse_VALUE = 280;
  /**
   * <code>GetClanRecommendListRequest = 281;</code>
   */
  public static final int GetClanRecommendListRequest_VALUE = 281;
  /**
   * <code>GetClanRecommendListResponse = 282;</code>
   */
  public static final int GetClanRecommendListResponse_VALUE = 282;
  /**
   * <code>ClanNoticeChangeRequest = 283;</code>
   */
  public static final int ClanNoticeChangeRequest_VALUE = 283;
  /**
   * <code>ClanNoticeChangeResponse = 284;</code>
   */
  public static final int ClanNoticeChangeResponse_VALUE = 284;
  /**
   * <code>ClanIntroductionChangeRequest = 285;</code>
   */
  public static final int ClanIntroductionChangeRequest_VALUE = 285;
  /**
   * <code>ClanIntroductionChangeResponse = 286;</code>
   */
  public static final int ClanIntroductionChangeResponse_VALUE = 286;
  /**
   * <code>ClanMemberRoleChangeRequest = 287;</code>
   */
  public static final int ClanMemberRoleChangeRequest_VALUE = 287;
  /**
   * <code>ClanMemberRoleChangeResponse = 288;</code>
   */
  public static final int ClanMemberRoleChangeResponse_VALUE = 288;
  /**
   * <code>ClanMemberRoleChangeNotify = 289;</code>
   */
  public static final int ClanMemberRoleChangeNotify_VALUE = 289;
  /**
   * <code>ClanMemberExpulsionRequest = 290;</code>
   */
  public static final int ClanMemberExpulsionRequest_VALUE = 290;
  /**
   * <code>ClanMemberExpulsionResponse = 291;</code>
   */
  public static final int ClanMemberExpulsionResponse_VALUE = 291;
  /**
   * <code>ClanMemberLeaveNotify = 292;</code>
   */
  public static final int ClanMemberLeaveNotify_VALUE = 292;
  /**
   * <code>ClanMemberExpulsionNotify = 293;</code>
   */
  public static final int ClanMemberExpulsionNotify_VALUE = 293;
  /**
   * <code>ClanMemberLeaveRequest = 294;</code>
   */
  public static final int ClanMemberLeaveRequest_VALUE = 294;
  /**
   * <code>ClanMemberLeaveResponse = 295;</code>
   */
  public static final int ClanMemberLeaveResponse_VALUE = 295;
  /**
   * <code>ClanNameChangeRequest = 296;</code>
   */
  public static final int ClanNameChangeRequest_VALUE = 296;
  /**
   * <code>ClanNameChangeResponse = 297;</code>
   */
  public static final int ClanNameChangeResponse_VALUE = 297;
  /**
   * <code>PlayerDonateClanRequest = 298;</code>
   */
  public static final int PlayerDonateClanRequest_VALUE = 298;
  /**
   * <code>PlayerDonateClanResponse = 299;</code>
   */
  public static final int PlayerDonateClanResponse_VALUE = 299;
  /**
   * <code>StoneStatueInfoRequest = 300;</code>
   */
  public static final int StoneStatueInfoRequest_VALUE = 300;
  /**
   * <code>StoneStatueInfoResponse = 301;</code>
   */
  public static final int StoneStatueInfoResponse_VALUE = 301;
  /**
   * <code>StoneStatueEnchantSlotLockRequest = 302;</code>
   */
  public static final int StoneStatueEnchantSlotLockRequest_VALUE = 302;
  /**
   * <code>StoneStatueEnchantSlotLockResponse = 303;</code>
   */
  public static final int StoneStatueEnchantSlotLockResponse_VALUE = 303;
  /**
   * <code>StoneStatueEnchantChangeSafeGradeRequest = 304;</code>
   */
  public static final int StoneStatueEnchantChangeSafeGradeRequest_VALUE = 304;
  /**
   * <code>StoneStatueEnchantChangeSafeGradeResponse = 305;</code>
   */
  public static final int StoneStatueEnchantChangeSafeGradeResponse_VALUE = 305;
  /**
   * <code>StoneStatueEnchantRequest = 306;</code>
   */
  public static final int StoneStatueEnchantRequest_VALUE = 306;
  /**
   * <code>StoneStatueEnchantResponse = 307;</code>
   */
  public static final int StoneStatueEnchantResponse_VALUE = 307;
  /**
   * <code>StoneStatueGemLevelUpRequest = 308;</code>
   */
  public static final int StoneStatueGemLevelUpRequest_VALUE = 308;
  /**
   * <code>StoneStatueGemLevelUpResponse = 309;</code>
   */
  public static final int StoneStatueGemLevelUpResponse_VALUE = 309;
  /**
   * <code>StoneStatueGemLimitLevelUpRequest = 310;</code>
   */
  public static final int StoneStatueGemLimitLevelUpRequest_VALUE = 310;
  /**
   * <code>StoneStatueGemLimitLevelUpResponse = 311;</code>
   */
  public static final int StoneStatueGemLimitLevelUpResponse_VALUE = 311;
  /**
   * <code>StoneStatueAvatarEquipRequest = 312;</code>
   */
  public static final int StoneStatueAvatarEquipRequest_VALUE = 312;
  /**
   * <code>StoneStatueAvatarEquipResponse = 313;</code>
   */
  public static final int StoneStatueAvatarEquipResponse_VALUE = 313;
  /**
   * <code>PlayerAdvertiseInfoRequest = 314;</code>
   */
  public static final int PlayerAdvertiseInfoRequest_VALUE = 314;
  /**
   * <code>PlayerAdvertiseInfoResponse = 315;</code>
   */
  public static final int PlayerAdvertiseInfoResponse_VALUE = 315;
  /**
   * <code>PlayerClanDissolutionRequest = 316;</code>
   */
  public static final int PlayerClanDissolutionRequest_VALUE = 316;
  /**
   * <code>PlayerClanDissolutionResponse = 317;</code>
   */
  public static final int PlayerClanDissolutionResponse_VALUE = 317;
  /**
   * <code>PlayerBlockFriendWithCodeRequest = 318;</code>
   */
  public static final int PlayerBlockFriendWithCodeRequest_VALUE = 318;
  /**
   * <code>PlayerBlockFriendWithCodeResponse = 319;</code>
   */
  public static final int PlayerBlockFriendWithCodeResponse_VALUE = 319;
  /**
   * <code>ChatNotify = 1000;</code>
   */
  public static final int ChatNotify_VALUE = 1000;
  /**
   * <code>ChatHistoryNotify = 1001;</code>
   */
  public static final int ChatHistoryNotify_VALUE = 1001;
  /**
   * <code>ChatRequest = 1002;</code>
   */
  public static final int ChatRequest_VALUE = 1002;
  /**
   * <code>ChatResponse = 1003;</code>
   */
  public static final int ChatResponse_VALUE = 1003;
  /**
   * <code>WhisperRequest = 1004;</code>
   */
  public static final int WhisperRequest_VALUE = 1004;
  /**
   * <code>WhisperResponse = 1005;</code>
   */
  public static final int WhisperResponse_VALUE = 1005;
  /**
   * <code>ChatHistoriesRequest = 1006;</code>
   */
  public static final int ChatHistoriesRequest_VALUE = 1006;
  /**
   * <code>ChatHistoriesResponse = 1007;</code>
   */
  public static final int ChatHistoriesResponse_VALUE = 1007;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PacketType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PacketType forNumber(int value) {
    switch (value) {
      case 0: return Ping;
      case 1: return LoginRequest;
      case 2: return LoginResponse;
      case 3: return ChangeEquipAvatarRequest;
      case 4: return ChangeEquipAvatarResponse;
      case 5: return GrowthLevelUpRequest;
      case 6: return GrowthLevelUpResponse;
      case 7: return GrowthPromoteRequest;
      case 8: return GrowthPromoteResponse;
      case 9: return GrowthLimitBreakRequest;
      case 10: return GrowthLimitBreakResponse;
      case 11: return PartsSlotLevelUpRequest;
      case 12: return PartsSlotLevelUpResponse;
      case 13: return GrowthEquipPartsRequest;
      case 14: return GrowthEquipPartsResponse;
      case 15: return LogoutRequest;
      case 16: return LogoutResponse;
      case 17: return LogoutNotify;
      case 18: return MailRequest;
      case 19: return MailResponse;
      case 20: return MailReadRequest;
      case 21: return MailReadResponse;
      case 22: return MailNotify;
      case 23: return CollectionLevelUpRequest;
      case 24: return CollectionLevelUpResponse;
      case 25: return CollectionRequest;
      case 26: return CollectionResponse;
      case 27: return SyncItemCountRequest;
      case 28: return SyncItemCountResponse;
      case 29: return PartsSlotRequest;
      case 30: return PartsSlotResponse;
      case 31: return StageClearSaveRequest;
      case 32: return StageClearSaveResponse;
      case 33: return ChangePortraitIconRequest;
      case 34: return ChangePortraitIconResponse;
      case 35: return ChangePlayerNameRequest;
      case 36: return ChangePlayerNameResponse;
      case 37: return StatsRequest;
      case 38: return StatsResponse;
      case 39: return CharacterStatGrowthRequest;
      case 40: return CharacterStatGrowthResponse;
      case 41: return CharacterStatGrowthLevelUpRequest;
      case 42: return CharacterStatGrowthLevelUpResponse;
      case 43: return EquipPresetRequest;
      case 44: return EquipPresetResponse;
      case 45: return EquipPresetEquipRequest;
      case 46: return EquipPresetEquipResponse;
      case 47: return EquipPresetUnEquipRequest;
      case 48: return EquipPresetUnEquipResponse;
      case 51: return EquipPresetNameChangeRequest;
      case 52: return EquipPresetNameChangeResponse;
      case 53: return EquipPresetIndexChangeRequest;
      case 54: return EquipPresetIndexChangeResponse;
      case 55: return StatsNotify;
      case 56: return PlayerLevelUpNotify;
      case 57: return DailyDungeonStartRequest;
      case 58: return DailyDungeonStartResponse;
      case 59: return DailyDungeonClearRequest;
      case 60: return DailyDungeonClearResponse;
      case 61: return DailyDungeonRequest;
      case 62: return DailyDungeonResponse;
      case 63: return DailyDungeonViewAdvertiseRequest;
      case 64: return DailyDungeonViewAdvertiseResponse;
      case 65: return RaidDungeonStartRequest;
      case 66: return RaidDungeonStartResponse;
      case 67: return RaidDungeonClearRequest;
      case 68: return RaidDungeonClearResponse;
      case 69: return RaidDungeonRequest;
      case 70: return RaidDungeonResponse;
      case 71: return RaidDungeonViewAdvertiseRequest;
      case 72: return RaidDungeonViewAdvertiseResponse;
      case 73: return TowerStartRequest;
      case 74: return TowerStartResponse;
      case 75: return TowerClearRequest;
      case 76: return TowerClearResponse;
      case 77: return TowerRequest;
      case 78: return TowerResponse;
      case 79: return CooperativeRaidDungeonRequest;
      case 80: return CooperativeRaidDungeonResponse;
      case 81: return CompetitiveRaidDungeonRequest;
      case 82: return CompetitiveRaidDungeonResponse;
      case 83: return CompetitiveRaidDungeonRankRequest;
      case 84: return CompetitiveRaidDungeonRankResponse;
      case 85: return FriendListRequest;
      case 86: return FriendListResponse;
      case 87: return AddFriendRequest;
      case 88: return AddFriendResponse;
      case 89: return DeleteFriendRequest;
      case 90: return DeleteFriendResponse;
      case 91: return GiveFriendGiftRequest;
      case 92: return GiveFriendGiftResponse;
      case 93: return SearchFriendRequest;
      case 94: return SearchFriendResponse;
      case 95: return AddFriendCancelRequest;
      case 96: return AddFriendCancelResponse;
      case 98: return RecommendFriendRequest;
      case 99: return RecommendFriendResponse;
      case 100: return AddFriendNotify;
      case 101: return DeleteFriendNotify;
      case 102: return ChangeFriendStateNotify;
      case 103: return BlockPlayerRequest;
      case 104: return BlockPlayerResponse;
      case 105: return UnBlockPlayerRequest;
      case 106: return UnBlockPlayerResponse;
      case 107: return PlayerBlockListRequest;
      case 108: return PlayerBlockListResponse;
      case 109: return CheatRequest;
      case 110: return CheatResponse;
      case 111: return ViewAdvertiseRequest;
      case 112: return ViewAdvertiseResponse;
      case 113: return AvatarNotify;
      case 114: return GrowthNotify;
      case 115: return ItemNotify;
      case 116: return StageNotify;
      case 117: return StageBossGaugeOnRequest;
      case 118: return StageBossGaugeOnResponse;
      case 120: return ViewExplorationNotify;
      case 121: return ExplorationStartRequest;
      case 122: return ExplorationStartResponse;
      case 123: return ExplorationEndRequest;
      case 124: return ExplorationEndResponse;
      case 125: return ExplorationChangeRequest;
      case 126: return ExplorationChangeResponse;
      case 127: return ViewExplorationCommercialRequest;
      case 128: return ViewExplorationCommercialResponse;
      case 129: return ExplorationCommercialRequest;
      case 130: return ExplorationCommercialResponse;
      case 131: return ExplorationAccelerationRequest;
      case 132: return ExplorationAccelerationResponse;
      case 133: return ExplorationEditAutoRequest;
      case 134: return ExplorationEditAutoResponse;
      case 135: return CurrencyNotify;
      case 136: return AttackPowerRankRequest;
      case 137: return AttackPowerRankResponse;
      case 138: return GetPlayerDetailInfoRequest;
      case 139: return GetPlayerDetailInfoResponse;
      case 140: return PlayerSpawnGachaRequest;
      case 141: return PlayerSpawnGachaResponse;
      case 142: return PlayerPickUpGachaRewardRequest;
      case 143: return PlayerPickUpGachaRewardResponse;
      case 144: return PlayerViewGachaCommercialRequest;
      case 145: return PlayerViewGachaCommercialResponse;
      case 146: return PlayerConditionPackageInfoRequest;
      case 147: return PlayerConditionPackageInfoResponse;
      case 148: return PlayerConditionPackageNotify;
      case 150: return DiggingRequest;
      case 151: return DiggingResponse;
      case 152: return DiggingUpgradeRequest;
      case 153: return DiggingUpgradeResponse;
      case 154: return DiggingUpgradeInfoRequest;
      case 155: return DiggingUpgradeInfoResponse;
      case 156: return DiggingCompleteRequest;
      case 157: return DiggingCompleteResponse;
      case 158: return ViewDiggingCommercialRequest;
      case 159: return ViewDiggingCommercialResponse;
      case 160: return UseAcceleratorRequest;
      case 161: return UseAcceleratorResponse;
      case 162: return DiggingInfoRequest;
      case 163: return DiggingInfoResponse;
      case 164: return UseMultiAcceleratorRequest;
      case 165: return UseMultiAcceleratorResponse;
      case 166: return PlayerGachaInfoRequest;
      case 167: return PlayerGachaInfoResponse;
      case 168: return PlayerShopItemInfoRequest;
      case 169: return PlayerShopItemInfoResponse;
      case 172: return PlayerPurchaseShopItemRequest;
      case 173: return PlayerPurchaseShopItemResponse;
      case 174: return PlayerShopPassInfoRequest;
      case 175: return PlayerShopPassInfoResponse;
      case 176: return PlayerShopPassRewardRequest;
      case 177: return PlayerShopPassRewardResponse;
      case 179: return AttackPowerRankNotify;
      case 180: return DuelRequest;
      case 181: return DuelResponse;
      case 200: return FarmInfoRequest;
      case 201: return FarmInfoResponse;
      case 202: return FarmPlantSeedRequest;
      case 203: return FarmPlantSeedResponse;
      case 204: return FarmPlantBoostRequest;
      case 205: return FarmPlantBoostResponse;
      case 206: return FarmPlantHarvestRequest;
      case 207: return FarmPlantHarvestResponse;
      case 208: return FarmStealRequest;
      case 209: return FarmStealResponse;
      case 210: return FarmReturnStolenPlantsToThiefRequest;
      case 211: return FarmReturnStolenPlantsToThiefResponse;
      case 212: return FarmRemoveThiefByBattleRequest;
      case 213: return FarmRemoveThiefByBattleResponse;
      case 214: return FarmHistoryListRequest;
      case 215: return FarmHistoryListResponse;
      case 216: return FarmFriendListRequest;
      case 217: return FarmFriendListResponse;
      case 218: return FarmOtherListRequest;
      case 219: return FarmOtherListResponse;
      case 220: return FarmCommercialInfoRequest;
      case 221: return FarmCommercialInfoResponse;
      case 222: return FarmCommercialSeedViewRequest;
      case 223: return FarmCommercialSeedViewResponse;
      case 224: return FarmCookInfoRequest;
      case 225: return FarmCookInfoResponse;
      case 226: return FarmCookRequest;
      case 227: return FarmCookResponse;
      case 228: return FarmCookCommercialViewRequest;
      case 229: return FarmCookCommercialViewResponse;
      case 230: return PortraitNotify;
      case 231: return FarmMyRestrictionsInfoRequest;
      case 232: return FarmMyRestrictionsInfoResponse;
      case 233: return FarmChangeNotify;
      case 234: return WorldEventRequest;
      case 235: return WorldEventResponse;
      case 236: return WorldEventNotify;
      case 237: return PlayerEventRequest;
      case 238: return PlayerEventResponse;
      case 239: return PlayerEventRewardRequest;
      case 240: return PlayerEventRewardResponse;
      case 241: return PlayerEventNotify;
      case 242: return PlayerDailyContentRequest;
      case 243: return PlayerDailyContentResponse;
      case 244: return PlayerDailyContentRewardRequest;
      case 245: return PlayerDailyContentRewardResponse;
      case 246: return PlayerDailyContentNotify;
      case 247: return PlayerAchievementRequest;
      case 248: return PlayerAchievementResponse;
      case 249: return PlayerAchievementNotify;
      case 250: return PlayerAchievementRewardRequest;
      case 251: return PlayerAchievementRewardResponse;
      case 252: return PlayerQuestRequest;
      case 253: return PlayerQuestResponse;
      case 254: return PlayerQuestRewardRequest;
      case 255: return PlayerQuestRewardResponse;
      case 256: return PlayerQuestNotify;
      case 257: return PlayerDuelHistorySaveRequest;
      case 258: return PlayerDuelHistorySaveResponse;
      case 259: return PlayerDuelHistoriesRequest;
      case 260: return PlayerDuelHistoriesResponse;
      case 261: return ClanJoinRequestListRequest;
      case 262: return ClanJoinRequestListResponse;
      case 263: return ClanJoinRequestReplyRequest;
      case 264: return ClanJoinRequestReplyResponse;
      case 265: return ClanJoinRequestReplyNotify;
      case 266: return AddFriendResponseRequest;
      case 267: return AddFriendResponseResponse;
      case 270: return CreateClanRequest;
      case 271: return CreateClanResponse;
      case 272: return ClanInfoRequest;
      case 273: return ClanInfoResponse;
      case 274: return PlayerClanJoinRequestListRequest;
      case 275: return PlayerClanJoinRequestListResponse;
      case 276: return PlayerClanJoinRequest;
      case 277: return PlayerClanJoinResponse;
      case 278: return PlayerClanJoinNotify;
      case 279: return ClanMemberListRequest;
      case 280: return ClanMemberListResponse;
      case 281: return GetClanRecommendListRequest;
      case 282: return GetClanRecommendListResponse;
      case 283: return ClanNoticeChangeRequest;
      case 284: return ClanNoticeChangeResponse;
      case 285: return ClanIntroductionChangeRequest;
      case 286: return ClanIntroductionChangeResponse;
      case 287: return ClanMemberRoleChangeRequest;
      case 288: return ClanMemberRoleChangeResponse;
      case 289: return ClanMemberRoleChangeNotify;
      case 290: return ClanMemberExpulsionRequest;
      case 291: return ClanMemberExpulsionResponse;
      case 292: return ClanMemberLeaveNotify;
      case 293: return ClanMemberExpulsionNotify;
      case 294: return ClanMemberLeaveRequest;
      case 295: return ClanMemberLeaveResponse;
      case 296: return ClanNameChangeRequest;
      case 297: return ClanNameChangeResponse;
      case 298: return PlayerDonateClanRequest;
      case 299: return PlayerDonateClanResponse;
      case 300: return StoneStatueInfoRequest;
      case 301: return StoneStatueInfoResponse;
      case 302: return StoneStatueEnchantSlotLockRequest;
      case 303: return StoneStatueEnchantSlotLockResponse;
      case 304: return StoneStatueEnchantChangeSafeGradeRequest;
      case 305: return StoneStatueEnchantChangeSafeGradeResponse;
      case 306: return StoneStatueEnchantRequest;
      case 307: return StoneStatueEnchantResponse;
      case 308: return StoneStatueGemLevelUpRequest;
      case 309: return StoneStatueGemLevelUpResponse;
      case 310: return StoneStatueGemLimitLevelUpRequest;
      case 311: return StoneStatueGemLimitLevelUpResponse;
      case 312: return StoneStatueAvatarEquipRequest;
      case 313: return StoneStatueAvatarEquipResponse;
      case 314: return PlayerAdvertiseInfoRequest;
      case 315: return PlayerAdvertiseInfoResponse;
      case 316: return PlayerClanDissolutionRequest;
      case 317: return PlayerClanDissolutionResponse;
      case 318: return PlayerBlockFriendWithCodeRequest;
      case 319: return PlayerBlockFriendWithCodeResponse;
      case 1000: return ChatNotify;
      case 1001: return ChatHistoryNotify;
      case 1002: return ChatRequest;
      case 1003: return ChatResponse;
      case 1004: return WhisperRequest;
      case 1005: return WhisperResponse;
      case 1006: return ChatHistoriesRequest;
      case 1007: return ChatHistoriesResponse;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PacketType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
          public PacketType findValueByNumber(int number) {
            return PacketType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.supercat.growstone.network.messages.NetEnum.getDescriptor().getEnumTypes().get(0);
  }

  private static final PacketType[] VALUES = values();

  public static PacketType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PacketType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PacketType)
}

