// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface TCharacterGrowthInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TCharacterGrowthInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ZPreset.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ZPreset.Type type = 1;</code>
   * @return The type.
   */
  com.supercat.growstone.network.messages.ZPreset.Type getType();

  /**
   * <code>repeated .TCharacterGrowthDetailInfo info = 2;</code>
   */
  java.util.List<com.supercat.growstone.network.messages.TCharacterGrowthDetailInfo> 
      getInfoList();
  /**
   * <code>repeated .TCharacterGrowthDetailInfo info = 2;</code>
   */
  com.supercat.growstone.network.messages.TCharacterGrowthDetailInfo getInfo(int index);
  /**
   * <code>repeated .TCharacterGrowthDetailInfo info = 2;</code>
   */
  int getInfoCount();
  /**
   * <code>repeated .TCharacterGrowthDetailInfo info = 2;</code>
   */
  java.util.List<? extends com.supercat.growstone.network.messages.TCharacterGrowthDetailInfoOrBuilder> 
      getInfoOrBuilderList();
  /**
   * <code>repeated .TCharacterGrowthDetailInfo info = 2;</code>
   */
  com.supercat.growstone.network.messages.TCharacterGrowthDetailInfoOrBuilder getInfoOrBuilder(
      int index);
}
