// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

/**
 * Protobuf type {@code TFarmBattleHistory}
 */
public final class TFarmBattleHistory extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TFarmBattleHistory)
    TFarmBattleHistoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TFarmBattleHistory.newBuilder() to construct.
  private TFarmBattleHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TFarmBattleHistory() {
    farmName_ = "";
    playerAName_ = "";
    playerBName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TFarmBattleHistory();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TFarmBattleHistory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            winnerPlayerId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            farmName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            playerAName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            playerBName_ = s;
            break;
          }
          case 40: {

            playerAPortraitId_ = input.readInt64();
            break;
          }
          case 48: {

            playerBPortraitId_ = input.readInt64();
            break;
          }
          case 56: {

            playerAAttackPower_ = input.readInt64();
            break;
          }
          case 64: {

            playerBAttackPower_ = input.readInt64();
            break;
          }
          case 72: {

            createdAt_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.supercat.growstone.network.messages.Network.internal_static_TFarmBattleHistory_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.supercat.growstone.network.messages.Network.internal_static_TFarmBattleHistory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.supercat.growstone.network.messages.TFarmBattleHistory.class, com.supercat.growstone.network.messages.TFarmBattleHistory.Builder.class);
  }

  public static final int WINNER_PLAYER_ID_FIELD_NUMBER = 1;
  private long winnerPlayerId_;
  /**
   * <pre>
   * 승자
   * </pre>
   *
   * <code>int64 winner_player_id = 1;</code>
   * @return The winnerPlayerId.
   */
  @java.lang.Override
  public long getWinnerPlayerId() {
    return winnerPlayerId_;
  }

  public static final int FARM_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object farmName_;
  /**
   * <pre>
   * 전투 장소
   * </pre>
   *
   * <code>string farm_name = 2;</code>
   * @return The farmName.
   */
  @java.lang.Override
  public java.lang.String getFarmName() {
    java.lang.Object ref = farmName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      farmName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 전투 장소
   * </pre>
   *
   * <code>string farm_name = 2;</code>
   * @return The bytes for farmName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFarmNameBytes() {
    java.lang.Object ref = farmName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      farmName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_A_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object playerAName_;
  /**
   * <code>string player_a_name = 3;</code>
   * @return The playerAName.
   */
  @java.lang.Override
  public java.lang.String getPlayerAName() {
    java.lang.Object ref = playerAName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerAName_ = s;
      return s;
    }
  }
  /**
   * <code>string player_a_name = 3;</code>
   * @return The bytes for playerAName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerANameBytes() {
    java.lang.Object ref = playerAName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerAName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_B_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object playerBName_;
  /**
   * <code>string player_b_name = 4;</code>
   * @return The playerBName.
   */
  @java.lang.Override
  public java.lang.String getPlayerBName() {
    java.lang.Object ref = playerBName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerBName_ = s;
      return s;
    }
  }
  /**
   * <code>string player_b_name = 4;</code>
   * @return The bytes for playerBName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerBNameBytes() {
    java.lang.Object ref = playerBName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerBName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_A_PORTRAIT_ID_FIELD_NUMBER = 5;
  private long playerAPortraitId_;
  /**
   * <code>int64 player_a_portrait_id = 5;</code>
   * @return The playerAPortraitId.
   */
  @java.lang.Override
  public long getPlayerAPortraitId() {
    return playerAPortraitId_;
  }

  public static final int PLAYER_B_PORTRAIT_ID_FIELD_NUMBER = 6;
  private long playerBPortraitId_;
  /**
   * <code>int64 player_b_portrait_id = 6;</code>
   * @return The playerBPortraitId.
   */
  @java.lang.Override
  public long getPlayerBPortraitId() {
    return playerBPortraitId_;
  }

  public static final int PLAYER_A_ATTACK_POWER_FIELD_NUMBER = 7;
  private long playerAAttackPower_;
  /**
   * <code>int64 player_a_attack_power = 7;</code>
   * @return The playerAAttackPower.
   */
  @java.lang.Override
  public long getPlayerAAttackPower() {
    return playerAAttackPower_;
  }

  public static final int PLAYER_B_ATTACK_POWER_FIELD_NUMBER = 8;
  private long playerBAttackPower_;
  /**
   * <code>int64 player_b_attack_power = 8;</code>
   * @return The playerBAttackPower.
   */
  @java.lang.Override
  public long getPlayerBAttackPower() {
    return playerBAttackPower_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 9;
  private long createdAt_;
  /**
   * <code>int64 created_at = 9;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (winnerPlayerId_ != 0L) {
      output.writeInt64(1, winnerPlayerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(farmName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, farmName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playerAName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, playerAName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playerBName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, playerBName_);
    }
    if (playerAPortraitId_ != 0L) {
      output.writeInt64(5, playerAPortraitId_);
    }
    if (playerBPortraitId_ != 0L) {
      output.writeInt64(6, playerBPortraitId_);
    }
    if (playerAAttackPower_ != 0L) {
      output.writeInt64(7, playerAAttackPower_);
    }
    if (playerBAttackPower_ != 0L) {
      output.writeInt64(8, playerBAttackPower_);
    }
    if (createdAt_ != 0L) {
      output.writeInt64(9, createdAt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (winnerPlayerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, winnerPlayerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(farmName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, farmName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playerAName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, playerAName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playerBName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, playerBName_);
    }
    if (playerAPortraitId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, playerAPortraitId_);
    }
    if (playerBPortraitId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, playerBPortraitId_);
    }
    if (playerAAttackPower_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, playerAAttackPower_);
    }
    if (playerBAttackPower_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, playerBAttackPower_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, createdAt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.supercat.growstone.network.messages.TFarmBattleHistory)) {
      return super.equals(obj);
    }
    com.supercat.growstone.network.messages.TFarmBattleHistory other = (com.supercat.growstone.network.messages.TFarmBattleHistory) obj;

    if (getWinnerPlayerId()
        != other.getWinnerPlayerId()) return false;
    if (!getFarmName()
        .equals(other.getFarmName())) return false;
    if (!getPlayerAName()
        .equals(other.getPlayerAName())) return false;
    if (!getPlayerBName()
        .equals(other.getPlayerBName())) return false;
    if (getPlayerAPortraitId()
        != other.getPlayerAPortraitId()) return false;
    if (getPlayerBPortraitId()
        != other.getPlayerBPortraitId()) return false;
    if (getPlayerAAttackPower()
        != other.getPlayerAAttackPower()) return false;
    if (getPlayerBAttackPower()
        != other.getPlayerBAttackPower()) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WINNER_PLAYER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWinnerPlayerId());
    hash = (37 * hash) + FARM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFarmName().hashCode();
    hash = (37 * hash) + PLAYER_A_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerAName().hashCode();
    hash = (37 * hash) + PLAYER_B_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerBName().hashCode();
    hash = (37 * hash) + PLAYER_A_PORTRAIT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerAPortraitId());
    hash = (37 * hash) + PLAYER_B_PORTRAIT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerBPortraitId());
    hash = (37 * hash) + PLAYER_A_ATTACK_POWER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerAAttackPower());
    hash = (37 * hash) + PLAYER_B_ATTACK_POWER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayerBAttackPower());
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.TFarmBattleHistory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.supercat.growstone.network.messages.TFarmBattleHistory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TFarmBattleHistory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TFarmBattleHistory)
      com.supercat.growstone.network.messages.TFarmBattleHistoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supercat.growstone.network.messages.Network.internal_static_TFarmBattleHistory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supercat.growstone.network.messages.Network.internal_static_TFarmBattleHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supercat.growstone.network.messages.TFarmBattleHistory.class, com.supercat.growstone.network.messages.TFarmBattleHistory.Builder.class);
    }

    // Construct using com.supercat.growstone.network.messages.TFarmBattleHistory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      winnerPlayerId_ = 0L;

      farmName_ = "";

      playerAName_ = "";

      playerBName_ = "";

      playerAPortraitId_ = 0L;

      playerBPortraitId_ = 0L;

      playerAAttackPower_ = 0L;

      playerBAttackPower_ = 0L;

      createdAt_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.supercat.growstone.network.messages.Network.internal_static_TFarmBattleHistory_descriptor;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.TFarmBattleHistory getDefaultInstanceForType() {
      return com.supercat.growstone.network.messages.TFarmBattleHistory.getDefaultInstance();
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.TFarmBattleHistory build() {
      com.supercat.growstone.network.messages.TFarmBattleHistory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.TFarmBattleHistory buildPartial() {
      com.supercat.growstone.network.messages.TFarmBattleHistory result = new com.supercat.growstone.network.messages.TFarmBattleHistory(this);
      result.winnerPlayerId_ = winnerPlayerId_;
      result.farmName_ = farmName_;
      result.playerAName_ = playerAName_;
      result.playerBName_ = playerBName_;
      result.playerAPortraitId_ = playerAPortraitId_;
      result.playerBPortraitId_ = playerBPortraitId_;
      result.playerAAttackPower_ = playerAAttackPower_;
      result.playerBAttackPower_ = playerBAttackPower_;
      result.createdAt_ = createdAt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.supercat.growstone.network.messages.TFarmBattleHistory) {
        return mergeFrom((com.supercat.growstone.network.messages.TFarmBattleHistory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.supercat.growstone.network.messages.TFarmBattleHistory other) {
      if (other == com.supercat.growstone.network.messages.TFarmBattleHistory.getDefaultInstance()) return this;
      if (other.getWinnerPlayerId() != 0L) {
        setWinnerPlayerId(other.getWinnerPlayerId());
      }
      if (!other.getFarmName().isEmpty()) {
        farmName_ = other.farmName_;
        onChanged();
      }
      if (!other.getPlayerAName().isEmpty()) {
        playerAName_ = other.playerAName_;
        onChanged();
      }
      if (!other.getPlayerBName().isEmpty()) {
        playerBName_ = other.playerBName_;
        onChanged();
      }
      if (other.getPlayerAPortraitId() != 0L) {
        setPlayerAPortraitId(other.getPlayerAPortraitId());
      }
      if (other.getPlayerBPortraitId() != 0L) {
        setPlayerBPortraitId(other.getPlayerBPortraitId());
      }
      if (other.getPlayerAAttackPower() != 0L) {
        setPlayerAAttackPower(other.getPlayerAAttackPower());
      }
      if (other.getPlayerBAttackPower() != 0L) {
        setPlayerBAttackPower(other.getPlayerBAttackPower());
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.supercat.growstone.network.messages.TFarmBattleHistory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.supercat.growstone.network.messages.TFarmBattleHistory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long winnerPlayerId_ ;
    /**
     * <pre>
     * 승자
     * </pre>
     *
     * <code>int64 winner_player_id = 1;</code>
     * @return The winnerPlayerId.
     */
    @java.lang.Override
    public long getWinnerPlayerId() {
      return winnerPlayerId_;
    }
    /**
     * <pre>
     * 승자
     * </pre>
     *
     * <code>int64 winner_player_id = 1;</code>
     * @param value The winnerPlayerId to set.
     * @return This builder for chaining.
     */
    public Builder setWinnerPlayerId(long value) {
      
      winnerPlayerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 승자
     * </pre>
     *
     * <code>int64 winner_player_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWinnerPlayerId() {
      
      winnerPlayerId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object farmName_ = "";
    /**
     * <pre>
     * 전투 장소
     * </pre>
     *
     * <code>string farm_name = 2;</code>
     * @return The farmName.
     */
    public java.lang.String getFarmName() {
      java.lang.Object ref = farmName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        farmName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 전투 장소
     * </pre>
     *
     * <code>string farm_name = 2;</code>
     * @return The bytes for farmName.
     */
    public com.google.protobuf.ByteString
        getFarmNameBytes() {
      java.lang.Object ref = farmName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        farmName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 전투 장소
     * </pre>
     *
     * <code>string farm_name = 2;</code>
     * @param value The farmName to set.
     * @return This builder for chaining.
     */
    public Builder setFarmName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      farmName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 전투 장소
     * </pre>
     *
     * <code>string farm_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFarmName() {
      
      farmName_ = getDefaultInstance().getFarmName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 전투 장소
     * </pre>
     *
     * <code>string farm_name = 2;</code>
     * @param value The bytes for farmName to set.
     * @return This builder for chaining.
     */
    public Builder setFarmNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      farmName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object playerAName_ = "";
    /**
     * <code>string player_a_name = 3;</code>
     * @return The playerAName.
     */
    public java.lang.String getPlayerAName() {
      java.lang.Object ref = playerAName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerAName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string player_a_name = 3;</code>
     * @return The bytes for playerAName.
     */
    public com.google.protobuf.ByteString
        getPlayerANameBytes() {
      java.lang.Object ref = playerAName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerAName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string player_a_name = 3;</code>
     * @param value The playerAName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerAName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerAName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string player_a_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerAName() {
      
      playerAName_ = getDefaultInstance().getPlayerAName();
      onChanged();
      return this;
    }
    /**
     * <code>string player_a_name = 3;</code>
     * @param value The bytes for playerAName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerANameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerAName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object playerBName_ = "";
    /**
     * <code>string player_b_name = 4;</code>
     * @return The playerBName.
     */
    public java.lang.String getPlayerBName() {
      java.lang.Object ref = playerBName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerBName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string player_b_name = 4;</code>
     * @return The bytes for playerBName.
     */
    public com.google.protobuf.ByteString
        getPlayerBNameBytes() {
      java.lang.Object ref = playerBName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerBName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string player_b_name = 4;</code>
     * @param value The playerBName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerBName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerBName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string player_b_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerBName() {
      
      playerBName_ = getDefaultInstance().getPlayerBName();
      onChanged();
      return this;
    }
    /**
     * <code>string player_b_name = 4;</code>
     * @param value The bytes for playerBName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerBNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerBName_ = value;
      onChanged();
      return this;
    }

    private long playerAPortraitId_ ;
    /**
     * <code>int64 player_a_portrait_id = 5;</code>
     * @return The playerAPortraitId.
     */
    @java.lang.Override
    public long getPlayerAPortraitId() {
      return playerAPortraitId_;
    }
    /**
     * <code>int64 player_a_portrait_id = 5;</code>
     * @param value The playerAPortraitId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerAPortraitId(long value) {
      
      playerAPortraitId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 player_a_portrait_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerAPortraitId() {
      
      playerAPortraitId_ = 0L;
      onChanged();
      return this;
    }

    private long playerBPortraitId_ ;
    /**
     * <code>int64 player_b_portrait_id = 6;</code>
     * @return The playerBPortraitId.
     */
    @java.lang.Override
    public long getPlayerBPortraitId() {
      return playerBPortraitId_;
    }
    /**
     * <code>int64 player_b_portrait_id = 6;</code>
     * @param value The playerBPortraitId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerBPortraitId(long value) {
      
      playerBPortraitId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 player_b_portrait_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerBPortraitId() {
      
      playerBPortraitId_ = 0L;
      onChanged();
      return this;
    }

    private long playerAAttackPower_ ;
    /**
     * <code>int64 player_a_attack_power = 7;</code>
     * @return The playerAAttackPower.
     */
    @java.lang.Override
    public long getPlayerAAttackPower() {
      return playerAAttackPower_;
    }
    /**
     * <code>int64 player_a_attack_power = 7;</code>
     * @param value The playerAAttackPower to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerAAttackPower(long value) {
      
      playerAAttackPower_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 player_a_attack_power = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerAAttackPower() {
      
      playerAAttackPower_ = 0L;
      onChanged();
      return this;
    }

    private long playerBAttackPower_ ;
    /**
     * <code>int64 player_b_attack_power = 8;</code>
     * @return The playerBAttackPower.
     */
    @java.lang.Override
    public long getPlayerBAttackPower() {
      return playerBAttackPower_;
    }
    /**
     * <code>int64 player_b_attack_power = 8;</code>
     * @param value The playerBAttackPower to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerBAttackPower(long value) {
      
      playerBAttackPower_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 player_b_attack_power = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerBAttackPower() {
      
      playerBAttackPower_ = 0L;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>int64 created_at = 9;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>int64 created_at = 9;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {
      
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 created_at = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      
      createdAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TFarmBattleHistory)
  }

  // @@protoc_insertion_point(class_scope:TFarmBattleHistory)
  private static final com.supercat.growstone.network.messages.TFarmBattleHistory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.supercat.growstone.network.messages.TFarmBattleHistory();
  }

  public static com.supercat.growstone.network.messages.TFarmBattleHistory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TFarmBattleHistory>
      PARSER = new com.google.protobuf.AbstractParser<TFarmBattleHistory>() {
    @java.lang.Override
    public TFarmBattleHistory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TFarmBattleHistory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TFarmBattleHistory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TFarmBattleHistory> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.supercat.growstone.network.messages.TFarmBattleHistory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

