// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface TRaidDungeonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TRaidDungeon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 score = 2;</code>
   * @return The score.
   */
  long getScore();

  /**
   * <code>int32 remain_ticket_count = 3;</code>
   * @return The remainTicketCount.
   */
  int getRemainTicketCount();

  /**
   * <code>int32 remain_ad_view_count = 4;</code>
   * @return The remainAdViewCount.
   */
  int getRemainAdViewCount();
}
