// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZChangeEquipAvatarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZChangeEquipAvatarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 avatar_id = 1;</code>
   * @return The avatarId.
   */
  long getAvatarId();
}
