// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetEnum.proto

package com.supercat.growstone.network.messages;

public interface ZClanMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZClanMember)
    com.google.protobuf.MessageOrBuilder {
}
