// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZCompetitiveRaidDungeonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZCompetitiveRaidDungeonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
