// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

/**
 * Protobuf type {@code ZCooperativeRaidDungeonResponse}
 */
public final class ZCooperativeRaidDungeonResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ZCooperativeRaidDungeonResponse)
    ZCooperativeRaidDungeonResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ZCooperativeRaidDungeonResponse.newBuilder() to construct.
  private ZCooperativeRaidDungeonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZCooperativeRaidDungeonResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZCooperativeRaidDungeonResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ZCooperativeRaidDungeonResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            status_ = input.readInt32();
            break;
          }
          case 18: {
            com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder subBuilder = null;
            if (cooperativeRaidInfo_ != null) {
              subBuilder = cooperativeRaidInfo_.toBuilder();
            }
            cooperativeRaidInfo_ = input.readMessage(com.supercat.growstone.network.messages.TCooperativeRaidDungeon.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cooperativeRaidInfo_);
              cooperativeRaidInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZCooperativeRaidDungeonResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZCooperativeRaidDungeonResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.class, com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int COOPERATIVE_RAID_INFO_FIELD_NUMBER = 2;
  private com.supercat.growstone.network.messages.TCooperativeRaidDungeon cooperativeRaidInfo_;
  /**
   * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
   * @return Whether the cooperativeRaidInfo field is set.
   */
  @java.lang.Override
  public boolean hasCooperativeRaidInfo() {
    return cooperativeRaidInfo_ != null;
  }
  /**
   * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
   * @return The cooperativeRaidInfo.
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TCooperativeRaidDungeon getCooperativeRaidInfo() {
    return cooperativeRaidInfo_ == null ? com.supercat.growstone.network.messages.TCooperativeRaidDungeon.getDefaultInstance() : cooperativeRaidInfo_;
  }
  /**
   * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TCooperativeRaidDungeonOrBuilder getCooperativeRaidInfoOrBuilder() {
    return getCooperativeRaidInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    if (cooperativeRaidInfo_ != null) {
      output.writeMessage(2, getCooperativeRaidInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    if (cooperativeRaidInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCooperativeRaidInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse)) {
      return super.equals(obj);
    }
    com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse other = (com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (hasCooperativeRaidInfo() != other.hasCooperativeRaidInfo()) return false;
    if (hasCooperativeRaidInfo()) {
      if (!getCooperativeRaidInfo()
          .equals(other.getCooperativeRaidInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    if (hasCooperativeRaidInfo()) {
      hash = (37 * hash) + COOPERATIVE_RAID_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getCooperativeRaidInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ZCooperativeRaidDungeonResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ZCooperativeRaidDungeonResponse)
      com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZCooperativeRaidDungeonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZCooperativeRaidDungeonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.class, com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.Builder.class);
    }

    // Construct using com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (cooperativeRaidInfoBuilder_ == null) {
        cooperativeRaidInfo_ = null;
      } else {
        cooperativeRaidInfo_ = null;
        cooperativeRaidInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZCooperativeRaidDungeonResponse_descriptor;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse getDefaultInstanceForType() {
      return com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse build() {
      com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse buildPartial() {
      com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse result = new com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse(this);
      result.status_ = status_;
      if (cooperativeRaidInfoBuilder_ == null) {
        result.cooperativeRaidInfo_ = cooperativeRaidInfo_;
      } else {
        result.cooperativeRaidInfo_ = cooperativeRaidInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse) {
        return mergeFrom((com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse other) {
      if (other == com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.hasCooperativeRaidInfo()) {
        mergeCooperativeRaidInfo(other.getCooperativeRaidInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.supercat.growstone.network.messages.TCooperativeRaidDungeon cooperativeRaidInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.supercat.growstone.network.messages.TCooperativeRaidDungeon, com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder, com.supercat.growstone.network.messages.TCooperativeRaidDungeonOrBuilder> cooperativeRaidInfoBuilder_;
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     * @return Whether the cooperativeRaidInfo field is set.
     */
    public boolean hasCooperativeRaidInfo() {
      return cooperativeRaidInfoBuilder_ != null || cooperativeRaidInfo_ != null;
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     * @return The cooperativeRaidInfo.
     */
    public com.supercat.growstone.network.messages.TCooperativeRaidDungeon getCooperativeRaidInfo() {
      if (cooperativeRaidInfoBuilder_ == null) {
        return cooperativeRaidInfo_ == null ? com.supercat.growstone.network.messages.TCooperativeRaidDungeon.getDefaultInstance() : cooperativeRaidInfo_;
      } else {
        return cooperativeRaidInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public Builder setCooperativeRaidInfo(com.supercat.growstone.network.messages.TCooperativeRaidDungeon value) {
      if (cooperativeRaidInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cooperativeRaidInfo_ = value;
        onChanged();
      } else {
        cooperativeRaidInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public Builder setCooperativeRaidInfo(
        com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder builderForValue) {
      if (cooperativeRaidInfoBuilder_ == null) {
        cooperativeRaidInfo_ = builderForValue.build();
        onChanged();
      } else {
        cooperativeRaidInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public Builder mergeCooperativeRaidInfo(com.supercat.growstone.network.messages.TCooperativeRaidDungeon value) {
      if (cooperativeRaidInfoBuilder_ == null) {
        if (cooperativeRaidInfo_ != null) {
          cooperativeRaidInfo_ =
            com.supercat.growstone.network.messages.TCooperativeRaidDungeon.newBuilder(cooperativeRaidInfo_).mergeFrom(value).buildPartial();
        } else {
          cooperativeRaidInfo_ = value;
        }
        onChanged();
      } else {
        cooperativeRaidInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public Builder clearCooperativeRaidInfo() {
      if (cooperativeRaidInfoBuilder_ == null) {
        cooperativeRaidInfo_ = null;
        onChanged();
      } else {
        cooperativeRaidInfo_ = null;
        cooperativeRaidInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder getCooperativeRaidInfoBuilder() {
      
      onChanged();
      return getCooperativeRaidInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    public com.supercat.growstone.network.messages.TCooperativeRaidDungeonOrBuilder getCooperativeRaidInfoOrBuilder() {
      if (cooperativeRaidInfoBuilder_ != null) {
        return cooperativeRaidInfoBuilder_.getMessageOrBuilder();
      } else {
        return cooperativeRaidInfo_ == null ?
            com.supercat.growstone.network.messages.TCooperativeRaidDungeon.getDefaultInstance() : cooperativeRaidInfo_;
      }
    }
    /**
     * <code>.TCooperativeRaidDungeon cooperative_raid_info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.supercat.growstone.network.messages.TCooperativeRaidDungeon, com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder, com.supercat.growstone.network.messages.TCooperativeRaidDungeonOrBuilder> 
        getCooperativeRaidInfoFieldBuilder() {
      if (cooperativeRaidInfoBuilder_ == null) {
        cooperativeRaidInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.supercat.growstone.network.messages.TCooperativeRaidDungeon, com.supercat.growstone.network.messages.TCooperativeRaidDungeon.Builder, com.supercat.growstone.network.messages.TCooperativeRaidDungeonOrBuilder>(
                getCooperativeRaidInfo(),
                getParentForChildren(),
                isClean());
        cooperativeRaidInfo_ = null;
      }
      return cooperativeRaidInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ZCooperativeRaidDungeonResponse)
  }

  // @@protoc_insertion_point(class_scope:ZCooperativeRaidDungeonResponse)
  private static final com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse();
  }

  public static com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ZCooperativeRaidDungeonResponse>
      PARSER = new com.google.protobuf.AbstractParser<ZCooperativeRaidDungeonResponse>() {
    @java.lang.Override
    public ZCooperativeRaidDungeonResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ZCooperativeRaidDungeonResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ZCooperativeRaidDungeonResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZCooperativeRaidDungeonResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.supercat.growstone.network.messages.ZCooperativeRaidDungeonResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

