// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZFarmCommercialInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZFarmCommercialInfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
