// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZFarmStealResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZFarmStealResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>.TFarm farm = 2;</code>
   * @return Whether the farm field is set.
   */
  boolean hasFarm();
  /**
   * <code>.TFarm farm = 2;</code>
   * @return The farm.
   */
  com.supercat.growstone.network.messages.TFarm getFarm();
  /**
   * <code>.TFarm farm = 2;</code>
   */
  com.supercat.growstone.network.messages.TFarmOrBuilder getFarmOrBuilder();
}
