// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZFarmInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZFarmInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 player_id = 1;</code>
   * @return The playerId.
   */
  int getPlayerId();
}
