// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZGetPlayerDetailInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZGetPlayerDetailInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 player_id = 1;</code>
   * @return The playerId.
   */
  long getPlayerId();
}
