// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

/**
 * Protobuf type {@code ZGrowthPromoteRequest}
 */
public final class ZGrowthPromoteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ZGrowthPromoteRequest)
    ZGrowthPromoteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ZGrowthPromoteRequest.newBuilder() to construct.
  private ZGrowthPromoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZGrowthPromoteRequest() {
    promoteTargets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZGrowthPromoteRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ZGrowthPromoteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              promoteTargets_ = new java.util.ArrayList<com.supercat.growstone.network.messages.TMaterial>();
              mutable_bitField0_ |= 0x00000001;
            }
            promoteTargets_.add(
                input.readMessage(com.supercat.growstone.network.messages.TMaterial.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        promoteTargets_ = java.util.Collections.unmodifiableList(promoteTargets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZGrowthPromoteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZGrowthPromoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.supercat.growstone.network.messages.ZGrowthPromoteRequest.class, com.supercat.growstone.network.messages.ZGrowthPromoteRequest.Builder.class);
  }

  public static final int PROMOTE_TARGETS_FIELD_NUMBER = 1;
  private java.util.List<com.supercat.growstone.network.messages.TMaterial> promoteTargets_;
  /**
   * <code>repeated .TMaterial promote_targets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.supercat.growstone.network.messages.TMaterial> getPromoteTargetsList() {
    return promoteTargets_;
  }
  /**
   * <code>repeated .TMaterial promote_targets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.supercat.growstone.network.messages.TMaterialOrBuilder> 
      getPromoteTargetsOrBuilderList() {
    return promoteTargets_;
  }
  /**
   * <code>repeated .TMaterial promote_targets = 1;</code>
   */
  @java.lang.Override
  public int getPromoteTargetsCount() {
    return promoteTargets_.size();
  }
  /**
   * <code>repeated .TMaterial promote_targets = 1;</code>
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TMaterial getPromoteTargets(int index) {
    return promoteTargets_.get(index);
  }
  /**
   * <code>repeated .TMaterial promote_targets = 1;</code>
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TMaterialOrBuilder getPromoteTargetsOrBuilder(
      int index) {
    return promoteTargets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < promoteTargets_.size(); i++) {
      output.writeMessage(1, promoteTargets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < promoteTargets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, promoteTargets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.supercat.growstone.network.messages.ZGrowthPromoteRequest)) {
      return super.equals(obj);
    }
    com.supercat.growstone.network.messages.ZGrowthPromoteRequest other = (com.supercat.growstone.network.messages.ZGrowthPromoteRequest) obj;

    if (!getPromoteTargetsList()
        .equals(other.getPromoteTargetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPromoteTargetsCount() > 0) {
      hash = (37 * hash) + PROMOTE_TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getPromoteTargetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.supercat.growstone.network.messages.ZGrowthPromoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ZGrowthPromoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ZGrowthPromoteRequest)
      com.supercat.growstone.network.messages.ZGrowthPromoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZGrowthPromoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZGrowthPromoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supercat.growstone.network.messages.ZGrowthPromoteRequest.class, com.supercat.growstone.network.messages.ZGrowthPromoteRequest.Builder.class);
    }

    // Construct using com.supercat.growstone.network.messages.ZGrowthPromoteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPromoteTargetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (promoteTargetsBuilder_ == null) {
        promoteTargets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        promoteTargetsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZGrowthPromoteRequest_descriptor;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZGrowthPromoteRequest getDefaultInstanceForType() {
      return com.supercat.growstone.network.messages.ZGrowthPromoteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZGrowthPromoteRequest build() {
      com.supercat.growstone.network.messages.ZGrowthPromoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZGrowthPromoteRequest buildPartial() {
      com.supercat.growstone.network.messages.ZGrowthPromoteRequest result = new com.supercat.growstone.network.messages.ZGrowthPromoteRequest(this);
      int from_bitField0_ = bitField0_;
      if (promoteTargetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          promoteTargets_ = java.util.Collections.unmodifiableList(promoteTargets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.promoteTargets_ = promoteTargets_;
      } else {
        result.promoteTargets_ = promoteTargetsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.supercat.growstone.network.messages.ZGrowthPromoteRequest) {
        return mergeFrom((com.supercat.growstone.network.messages.ZGrowthPromoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.supercat.growstone.network.messages.ZGrowthPromoteRequest other) {
      if (other == com.supercat.growstone.network.messages.ZGrowthPromoteRequest.getDefaultInstance()) return this;
      if (promoteTargetsBuilder_ == null) {
        if (!other.promoteTargets_.isEmpty()) {
          if (promoteTargets_.isEmpty()) {
            promoteTargets_ = other.promoteTargets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePromoteTargetsIsMutable();
            promoteTargets_.addAll(other.promoteTargets_);
          }
          onChanged();
        }
      } else {
        if (!other.promoteTargets_.isEmpty()) {
          if (promoteTargetsBuilder_.isEmpty()) {
            promoteTargetsBuilder_.dispose();
            promoteTargetsBuilder_ = null;
            promoteTargets_ = other.promoteTargets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            promoteTargetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPromoteTargetsFieldBuilder() : null;
          } else {
            promoteTargetsBuilder_.addAllMessages(other.promoteTargets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.supercat.growstone.network.messages.ZGrowthPromoteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.supercat.growstone.network.messages.ZGrowthPromoteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.supercat.growstone.network.messages.TMaterial> promoteTargets_ =
      java.util.Collections.emptyList();
    private void ensurePromoteTargetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        promoteTargets_ = new java.util.ArrayList<com.supercat.growstone.network.messages.TMaterial>(promoteTargets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.supercat.growstone.network.messages.TMaterial, com.supercat.growstone.network.messages.TMaterial.Builder, com.supercat.growstone.network.messages.TMaterialOrBuilder> promoteTargetsBuilder_;

    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public java.util.List<com.supercat.growstone.network.messages.TMaterial> getPromoteTargetsList() {
      if (promoteTargetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(promoteTargets_);
      } else {
        return promoteTargetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public int getPromoteTargetsCount() {
      if (promoteTargetsBuilder_ == null) {
        return promoteTargets_.size();
      } else {
        return promoteTargetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public com.supercat.growstone.network.messages.TMaterial getPromoteTargets(int index) {
      if (promoteTargetsBuilder_ == null) {
        return promoteTargets_.get(index);
      } else {
        return promoteTargetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder setPromoteTargets(
        int index, com.supercat.growstone.network.messages.TMaterial value) {
      if (promoteTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePromoteTargetsIsMutable();
        promoteTargets_.set(index, value);
        onChanged();
      } else {
        promoteTargetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder setPromoteTargets(
        int index, com.supercat.growstone.network.messages.TMaterial.Builder builderForValue) {
      if (promoteTargetsBuilder_ == null) {
        ensurePromoteTargetsIsMutable();
        promoteTargets_.set(index, builderForValue.build());
        onChanged();
      } else {
        promoteTargetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder addPromoteTargets(com.supercat.growstone.network.messages.TMaterial value) {
      if (promoteTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePromoteTargetsIsMutable();
        promoteTargets_.add(value);
        onChanged();
      } else {
        promoteTargetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder addPromoteTargets(
        int index, com.supercat.growstone.network.messages.TMaterial value) {
      if (promoteTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePromoteTargetsIsMutable();
        promoteTargets_.add(index, value);
        onChanged();
      } else {
        promoteTargetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder addPromoteTargets(
        com.supercat.growstone.network.messages.TMaterial.Builder builderForValue) {
      if (promoteTargetsBuilder_ == null) {
        ensurePromoteTargetsIsMutable();
        promoteTargets_.add(builderForValue.build());
        onChanged();
      } else {
        promoteTargetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder addPromoteTargets(
        int index, com.supercat.growstone.network.messages.TMaterial.Builder builderForValue) {
      if (promoteTargetsBuilder_ == null) {
        ensurePromoteTargetsIsMutable();
        promoteTargets_.add(index, builderForValue.build());
        onChanged();
      } else {
        promoteTargetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder addAllPromoteTargets(
        java.lang.Iterable<? extends com.supercat.growstone.network.messages.TMaterial> values) {
      if (promoteTargetsBuilder_ == null) {
        ensurePromoteTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, promoteTargets_);
        onChanged();
      } else {
        promoteTargetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder clearPromoteTargets() {
      if (promoteTargetsBuilder_ == null) {
        promoteTargets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        promoteTargetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public Builder removePromoteTargets(int index) {
      if (promoteTargetsBuilder_ == null) {
        ensurePromoteTargetsIsMutable();
        promoteTargets_.remove(index);
        onChanged();
      } else {
        promoteTargetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public com.supercat.growstone.network.messages.TMaterial.Builder getPromoteTargetsBuilder(
        int index) {
      return getPromoteTargetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public com.supercat.growstone.network.messages.TMaterialOrBuilder getPromoteTargetsOrBuilder(
        int index) {
      if (promoteTargetsBuilder_ == null) {
        return promoteTargets_.get(index);  } else {
        return promoteTargetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public java.util.List<? extends com.supercat.growstone.network.messages.TMaterialOrBuilder> 
         getPromoteTargetsOrBuilderList() {
      if (promoteTargetsBuilder_ != null) {
        return promoteTargetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(promoteTargets_);
      }
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public com.supercat.growstone.network.messages.TMaterial.Builder addPromoteTargetsBuilder() {
      return getPromoteTargetsFieldBuilder().addBuilder(
          com.supercat.growstone.network.messages.TMaterial.getDefaultInstance());
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public com.supercat.growstone.network.messages.TMaterial.Builder addPromoteTargetsBuilder(
        int index) {
      return getPromoteTargetsFieldBuilder().addBuilder(
          index, com.supercat.growstone.network.messages.TMaterial.getDefaultInstance());
    }
    /**
     * <code>repeated .TMaterial promote_targets = 1;</code>
     */
    public java.util.List<com.supercat.growstone.network.messages.TMaterial.Builder> 
         getPromoteTargetsBuilderList() {
      return getPromoteTargetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.supercat.growstone.network.messages.TMaterial, com.supercat.growstone.network.messages.TMaterial.Builder, com.supercat.growstone.network.messages.TMaterialOrBuilder> 
        getPromoteTargetsFieldBuilder() {
      if (promoteTargetsBuilder_ == null) {
        promoteTargetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.supercat.growstone.network.messages.TMaterial, com.supercat.growstone.network.messages.TMaterial.Builder, com.supercat.growstone.network.messages.TMaterialOrBuilder>(
                promoteTargets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        promoteTargets_ = null;
      }
      return promoteTargetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ZGrowthPromoteRequest)
  }

  // @@protoc_insertion_point(class_scope:ZGrowthPromoteRequest)
  private static final com.supercat.growstone.network.messages.ZGrowthPromoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.supercat.growstone.network.messages.ZGrowthPromoteRequest();
  }

  public static com.supercat.growstone.network.messages.ZGrowthPromoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ZGrowthPromoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ZGrowthPromoteRequest>() {
    @java.lang.Override
    public ZGrowthPromoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ZGrowthPromoteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ZGrowthPromoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZGrowthPromoteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.supercat.growstone.network.messages.ZGrowthPromoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

