// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZMailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZMailRequest)
    com.google.protobuf.MessageOrBuilder {
}
