// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPartsSlotLevelUpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPartsSlotLevelUpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ZPartsSlot.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ZPartsSlot.Type type = 1;</code>
   * @return The type.
   */
  com.supercat.growstone.network.messages.ZPartsSlot.Type getType();

  /**
   * <code>int32 level_up_count = 2;</code>
   * @return The levelUpCount.
   */
  int getLevelUpCount();
}
