// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerAchievementNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerAchievementNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TAchievements achievements = 1;</code>
   * @return Whether the achievements field is set.
   */
  boolean hasAchievements();
  /**
   * <code>.TAchievements achievements = 1;</code>
   * @return The achievements.
   */
  com.supercat.growstone.network.messages.TAchievements getAchievements();
  /**
   * <code>.TAchievements achievements = 1;</code>
   */
  com.supercat.growstone.network.messages.TAchievementsOrBuilder getAchievementsOrBuilder();
}
