// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerShopPassRewardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerShopPassRewardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 shop_pass_data_id = 1;</code>
   * @return The shopPassDataId.
   */
  long getShopPassDataId();

  /**
   * <code>.ZShopPassReward.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ZShopPassReward.Type type = 2;</code>
   * @return The type.
   */
  com.supercat.growstone.network.messages.ZShopPassReward.Type getType();

  /**
   * <code>int32 step = 3;</code>
   * @return The step.
   */
  int getStep();
}
