// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerDuelHistorySaveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerDuelHistorySaveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TPlayerDuelHistory history = 1;</code>
   * @return Whether the history field is set.
   */
  boolean hasHistory();
  /**
   * <code>.TPlayerDuelHistory history = 1;</code>
   * @return The history.
   */
  com.supercat.growstone.network.messages.TPlayerDuelHistory getHistory();
  /**
   * <code>.TPlayerDuelHistory history = 1;</code>
   */
  com.supercat.growstone.network.messages.TPlayerDuelHistoryOrBuilder getHistoryOrBuilder();
}
