// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerConditionPackageInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerConditionPackageInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated .TConditionPackage condition_packages = 2;</code>
   */
  java.util.List<com.supercat.growstone.network.messages.TConditionPackage> 
      getConditionPackagesList();
  /**
   * <code>repeated .TConditionPackage condition_packages = 2;</code>
   */
  com.supercat.growstone.network.messages.TConditionPackage getConditionPackages(int index);
  /**
   * <code>repeated .TConditionPackage condition_packages = 2;</code>
   */
  int getConditionPackagesCount();
  /**
   * <code>repeated .TConditionPackage condition_packages = 2;</code>
   */
  java.util.List<? extends com.supercat.growstone.network.messages.TConditionPackageOrBuilder> 
      getConditionPackagesOrBuilderList();
  /**
   * <code>repeated .TConditionPackage condition_packages = 2;</code>
   */
  com.supercat.growstone.network.messages.TConditionPackageOrBuilder getConditionPackagesOrBuilder(
      int index);
}
