// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerAdvertiseInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerAdvertiseInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated .TAdvertiseInfo advertise_infos = 2;</code>
   */
  java.util.List<com.supercat.growstone.network.messages.TAdvertiseInfo> 
      getAdvertiseInfosList();
  /**
   * <code>repeated .TAdvertiseInfo advertise_infos = 2;</code>
   */
  com.supercat.growstone.network.messages.TAdvertiseInfo getAdvertiseInfos(int index);
  /**
   * <code>repeated .TAdvertiseInfo advertise_infos = 2;</code>
   */
  int getAdvertiseInfosCount();
  /**
   * <code>repeated .TAdvertiseInfo advertise_infos = 2;</code>
   */
  java.util.List<? extends com.supercat.growstone.network.messages.TAdvertiseInfoOrBuilder> 
      getAdvertiseInfosOrBuilderList();
  /**
   * <code>repeated .TAdvertiseInfo advertise_infos = 2;</code>
   */
  com.supercat.growstone.network.messages.TAdvertiseInfoOrBuilder getAdvertiseInfosOrBuilder(
      int index);
}
