// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPlayerLevelUpNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPlayerLevelUpNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int64 exp = 2;</code>
   * @return The exp.
   */
  long getExp();
}
