// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZPortraitNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZPortraitNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TPortraitIcon portrait_icons = 1;</code>
   */
  java.util.List<com.supercat.growstone.network.messages.TPortraitIcon> 
      getPortraitIconsList();
  /**
   * <code>repeated .TPortraitIcon portrait_icons = 1;</code>
   */
  com.supercat.growstone.network.messages.TPortraitIcon getPortraitIcons(int index);
  /**
   * <code>repeated .TPortraitIcon portrait_icons = 1;</code>
   */
  int getPortraitIconsCount();
  /**
   * <code>repeated .TPortraitIcon portrait_icons = 1;</code>
   */
  java.util.List<? extends com.supercat.growstone.network.messages.TPortraitIconOrBuilder> 
      getPortraitIconsOrBuilderList();
  /**
   * <code>repeated .TPortraitIcon portrait_icons = 1;</code>
   */
  com.supercat.growstone.network.messages.TPortraitIconOrBuilder getPortraitIconsOrBuilder(
      int index);
}
