// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

/**
 * Protobuf type {@code ZRaidDungeonResponse}
 */
public final class ZRaidDungeonResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ZRaidDungeonResponse)
    ZRaidDungeonResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ZRaidDungeonResponse.newBuilder() to construct.
  private ZRaidDungeonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZRaidDungeonResponse() {
    raidDungeon_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZRaidDungeonResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ZRaidDungeonResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            status_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              raidDungeon_ = new java.util.ArrayList<com.supercat.growstone.network.messages.TRaidDungeon>();
              mutable_bitField0_ |= 0x00000001;
            }
            raidDungeon_.add(
                input.readMessage(com.supercat.growstone.network.messages.TRaidDungeon.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        raidDungeon_ = java.util.Collections.unmodifiableList(raidDungeon_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZRaidDungeonResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.supercat.growstone.network.messages.Network.internal_static_ZRaidDungeonResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.supercat.growstone.network.messages.ZRaidDungeonResponse.class, com.supercat.growstone.network.messages.ZRaidDungeonResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int RAID_DUNGEON_FIELD_NUMBER = 2;
  private java.util.List<com.supercat.growstone.network.messages.TRaidDungeon> raidDungeon_;
  /**
   * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.supercat.growstone.network.messages.TRaidDungeon> getRaidDungeonList() {
    return raidDungeon_;
  }
  /**
   * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.supercat.growstone.network.messages.TRaidDungeonOrBuilder> 
      getRaidDungeonOrBuilderList() {
    return raidDungeon_;
  }
  /**
   * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
   */
  @java.lang.Override
  public int getRaidDungeonCount() {
    return raidDungeon_.size();
  }
  /**
   * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TRaidDungeon getRaidDungeon(int index) {
    return raidDungeon_.get(index);
  }
  /**
   * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
   */
  @java.lang.Override
  public com.supercat.growstone.network.messages.TRaidDungeonOrBuilder getRaidDungeonOrBuilder(
      int index) {
    return raidDungeon_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeInt32(1, status_);
    }
    for (int i = 0; i < raidDungeon_.size(); i++) {
      output.writeMessage(2, raidDungeon_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, status_);
    }
    for (int i = 0; i < raidDungeon_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, raidDungeon_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.supercat.growstone.network.messages.ZRaidDungeonResponse)) {
      return super.equals(obj);
    }
    com.supercat.growstone.network.messages.ZRaidDungeonResponse other = (com.supercat.growstone.network.messages.ZRaidDungeonResponse) obj;

    if (getStatus()
        != other.getStatus()) return false;
    if (!getRaidDungeonList()
        .equals(other.getRaidDungeonList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    if (getRaidDungeonCount() > 0) {
      hash = (37 * hash) + RAID_DUNGEON_FIELD_NUMBER;
      hash = (53 * hash) + getRaidDungeonList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.supercat.growstone.network.messages.ZRaidDungeonResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ZRaidDungeonResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ZRaidDungeonResponse)
      com.supercat.growstone.network.messages.ZRaidDungeonResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZRaidDungeonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZRaidDungeonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.supercat.growstone.network.messages.ZRaidDungeonResponse.class, com.supercat.growstone.network.messages.ZRaidDungeonResponse.Builder.class);
    }

    // Construct using com.supercat.growstone.network.messages.ZRaidDungeonResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRaidDungeonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (raidDungeonBuilder_ == null) {
        raidDungeon_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        raidDungeonBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.supercat.growstone.network.messages.Network.internal_static_ZRaidDungeonResponse_descriptor;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZRaidDungeonResponse getDefaultInstanceForType() {
      return com.supercat.growstone.network.messages.ZRaidDungeonResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZRaidDungeonResponse build() {
      com.supercat.growstone.network.messages.ZRaidDungeonResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.supercat.growstone.network.messages.ZRaidDungeonResponse buildPartial() {
      com.supercat.growstone.network.messages.ZRaidDungeonResponse result = new com.supercat.growstone.network.messages.ZRaidDungeonResponse(this);
      int from_bitField0_ = bitField0_;
      result.status_ = status_;
      if (raidDungeonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          raidDungeon_ = java.util.Collections.unmodifiableList(raidDungeon_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.raidDungeon_ = raidDungeon_;
      } else {
        result.raidDungeon_ = raidDungeonBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.supercat.growstone.network.messages.ZRaidDungeonResponse) {
        return mergeFrom((com.supercat.growstone.network.messages.ZRaidDungeonResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.supercat.growstone.network.messages.ZRaidDungeonResponse other) {
      if (other == com.supercat.growstone.network.messages.ZRaidDungeonResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (raidDungeonBuilder_ == null) {
        if (!other.raidDungeon_.isEmpty()) {
          if (raidDungeon_.isEmpty()) {
            raidDungeon_ = other.raidDungeon_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRaidDungeonIsMutable();
            raidDungeon_.addAll(other.raidDungeon_);
          }
          onChanged();
        }
      } else {
        if (!other.raidDungeon_.isEmpty()) {
          if (raidDungeonBuilder_.isEmpty()) {
            raidDungeonBuilder_.dispose();
            raidDungeonBuilder_ = null;
            raidDungeon_ = other.raidDungeon_;
            bitField0_ = (bitField0_ & ~0x00000001);
            raidDungeonBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRaidDungeonFieldBuilder() : null;
          } else {
            raidDungeonBuilder_.addAllMessages(other.raidDungeon_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.supercat.growstone.network.messages.ZRaidDungeonResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.supercat.growstone.network.messages.ZRaidDungeonResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ ;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.supercat.growstone.network.messages.TRaidDungeon> raidDungeon_ =
      java.util.Collections.emptyList();
    private void ensureRaidDungeonIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        raidDungeon_ = new java.util.ArrayList<com.supercat.growstone.network.messages.TRaidDungeon>(raidDungeon_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.supercat.growstone.network.messages.TRaidDungeon, com.supercat.growstone.network.messages.TRaidDungeon.Builder, com.supercat.growstone.network.messages.TRaidDungeonOrBuilder> raidDungeonBuilder_;

    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public java.util.List<com.supercat.growstone.network.messages.TRaidDungeon> getRaidDungeonList() {
      if (raidDungeonBuilder_ == null) {
        return java.util.Collections.unmodifiableList(raidDungeon_);
      } else {
        return raidDungeonBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public int getRaidDungeonCount() {
      if (raidDungeonBuilder_ == null) {
        return raidDungeon_.size();
      } else {
        return raidDungeonBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public com.supercat.growstone.network.messages.TRaidDungeon getRaidDungeon(int index) {
      if (raidDungeonBuilder_ == null) {
        return raidDungeon_.get(index);
      } else {
        return raidDungeonBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder setRaidDungeon(
        int index, com.supercat.growstone.network.messages.TRaidDungeon value) {
      if (raidDungeonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaidDungeonIsMutable();
        raidDungeon_.set(index, value);
        onChanged();
      } else {
        raidDungeonBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder setRaidDungeon(
        int index, com.supercat.growstone.network.messages.TRaidDungeon.Builder builderForValue) {
      if (raidDungeonBuilder_ == null) {
        ensureRaidDungeonIsMutable();
        raidDungeon_.set(index, builderForValue.build());
        onChanged();
      } else {
        raidDungeonBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder addRaidDungeon(com.supercat.growstone.network.messages.TRaidDungeon value) {
      if (raidDungeonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaidDungeonIsMutable();
        raidDungeon_.add(value);
        onChanged();
      } else {
        raidDungeonBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder addRaidDungeon(
        int index, com.supercat.growstone.network.messages.TRaidDungeon value) {
      if (raidDungeonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaidDungeonIsMutable();
        raidDungeon_.add(index, value);
        onChanged();
      } else {
        raidDungeonBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder addRaidDungeon(
        com.supercat.growstone.network.messages.TRaidDungeon.Builder builderForValue) {
      if (raidDungeonBuilder_ == null) {
        ensureRaidDungeonIsMutable();
        raidDungeon_.add(builderForValue.build());
        onChanged();
      } else {
        raidDungeonBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder addRaidDungeon(
        int index, com.supercat.growstone.network.messages.TRaidDungeon.Builder builderForValue) {
      if (raidDungeonBuilder_ == null) {
        ensureRaidDungeonIsMutable();
        raidDungeon_.add(index, builderForValue.build());
        onChanged();
      } else {
        raidDungeonBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder addAllRaidDungeon(
        java.lang.Iterable<? extends com.supercat.growstone.network.messages.TRaidDungeon> values) {
      if (raidDungeonBuilder_ == null) {
        ensureRaidDungeonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, raidDungeon_);
        onChanged();
      } else {
        raidDungeonBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder clearRaidDungeon() {
      if (raidDungeonBuilder_ == null) {
        raidDungeon_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        raidDungeonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public Builder removeRaidDungeon(int index) {
      if (raidDungeonBuilder_ == null) {
        ensureRaidDungeonIsMutable();
        raidDungeon_.remove(index);
        onChanged();
      } else {
        raidDungeonBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public com.supercat.growstone.network.messages.TRaidDungeon.Builder getRaidDungeonBuilder(
        int index) {
      return getRaidDungeonFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public com.supercat.growstone.network.messages.TRaidDungeonOrBuilder getRaidDungeonOrBuilder(
        int index) {
      if (raidDungeonBuilder_ == null) {
        return raidDungeon_.get(index);  } else {
        return raidDungeonBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public java.util.List<? extends com.supercat.growstone.network.messages.TRaidDungeonOrBuilder> 
         getRaidDungeonOrBuilderList() {
      if (raidDungeonBuilder_ != null) {
        return raidDungeonBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(raidDungeon_);
      }
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public com.supercat.growstone.network.messages.TRaidDungeon.Builder addRaidDungeonBuilder() {
      return getRaidDungeonFieldBuilder().addBuilder(
          com.supercat.growstone.network.messages.TRaidDungeon.getDefaultInstance());
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public com.supercat.growstone.network.messages.TRaidDungeon.Builder addRaidDungeonBuilder(
        int index) {
      return getRaidDungeonFieldBuilder().addBuilder(
          index, com.supercat.growstone.network.messages.TRaidDungeon.getDefaultInstance());
    }
    /**
     * <code>repeated .TRaidDungeon raid_dungeon = 2;</code>
     */
    public java.util.List<com.supercat.growstone.network.messages.TRaidDungeon.Builder> 
         getRaidDungeonBuilderList() {
      return getRaidDungeonFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.supercat.growstone.network.messages.TRaidDungeon, com.supercat.growstone.network.messages.TRaidDungeon.Builder, com.supercat.growstone.network.messages.TRaidDungeonOrBuilder> 
        getRaidDungeonFieldBuilder() {
      if (raidDungeonBuilder_ == null) {
        raidDungeonBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.supercat.growstone.network.messages.TRaidDungeon, com.supercat.growstone.network.messages.TRaidDungeon.Builder, com.supercat.growstone.network.messages.TRaidDungeonOrBuilder>(
                raidDungeon_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        raidDungeon_ = null;
      }
      return raidDungeonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ZRaidDungeonResponse)
  }

  // @@protoc_insertion_point(class_scope:ZRaidDungeonResponse)
  private static final com.supercat.growstone.network.messages.ZRaidDungeonResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.supercat.growstone.network.messages.ZRaidDungeonResponse();
  }

  public static com.supercat.growstone.network.messages.ZRaidDungeonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ZRaidDungeonResponse>
      PARSER = new com.google.protobuf.AbstractParser<ZRaidDungeonResponse>() {
    @java.lang.Override
    public ZRaidDungeonResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ZRaidDungeonResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ZRaidDungeonResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZRaidDungeonResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.supercat.growstone.network.messages.ZRaidDungeonResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

