// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZRecommendFriendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZRecommendFriendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated .TPlayerSimpleInfo friends = 2;</code>
   */
  java.util.List<com.supercat.growstone.network.messages.TPlayerSimpleInfo> 
      getFriendsList();
  /**
   * <code>repeated .TPlayerSimpleInfo friends = 2;</code>
   */
  com.supercat.growstone.network.messages.TPlayerSimpleInfo getFriends(int index);
  /**
   * <code>repeated .TPlayerSimpleInfo friends = 2;</code>
   */
  int getFriendsCount();
  /**
   * <code>repeated .TPlayerSimpleInfo friends = 2;</code>
   */
  java.util.List<? extends com.supercat.growstone.network.messages.TPlayerSimpleInfoOrBuilder> 
      getFriendsOrBuilderList();
  /**
   * <code>repeated .TPlayerSimpleInfo friends = 2;</code>
   */
  com.supercat.growstone.network.messages.TPlayerSimpleInfoOrBuilder getFriendsOrBuilder(
      int index);
}
