// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZStageClearSaveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZStageClearSaveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>.TNextStageInfo next_stage_info = 2;</code>
   * @return Whether the nextStageInfo field is set.
   */
  boolean hasNextStageInfo();
  /**
   * <code>.TNextStageInfo next_stage_info = 2;</code>
   * @return The nextStageInfo.
   */
  com.supercat.growstone.network.messages.TNextStageInfo getNextStageInfo();
  /**
   * <code>.TNextStageInfo next_stage_info = 2;</code>
   */
  com.supercat.growstone.network.messages.TNextStageInfoOrBuilder getNextStageInfoOrBuilder();
}
