// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Network.proto

package com.supercat.growstone.network.messages;

public interface ZViewDiggingCommercialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZViewDiggingCommercialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 view_count = 2;</code>
   * @return The viewCount.
   */
  int getViewCount();

  /**
   * <code>.TItem tItem = 3;</code>
   * @return Whether the tItem field is set.
   */
  boolean hasTItem();
  /**
   * <code>.TItem tItem = 3;</code>
   * @return The tItem.
   */
  com.supercat.growstone.network.messages.TItem getTItem();
  /**
   * <code>.TItem tItem = 3;</code>
   */
  com.supercat.growstone.network.messages.TItemOrBuilder getTItemOrBuilder();
}
